### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/xxx/codebases/dvclive/train/loss.tsv'

### ISSUE THREAD

**Issue by zhouzaida** [iterative/dvclive#101]
If the name contains `/`  like 'train/loss', `self.log` will raise FileNotFoundError

https://github.com/iterative/dvclive/blob/8b260ae19a834b693ca8853b6d12140ec695effc/dvclive/metrics.py#L108-L130

https://github.com/iterative/dvclive/blob/8b260ae19a834b693ca8853b6d12140ec695effc/dvclive/serialize.py#L7-L15

**Comment by zhouzaida** [comment]
Should I convert the 'train/loss' to 'train-loss' in my codebase or it can be handled this in dvclive

**Comment by daavoo** [comment]
It should be fixed once #97 gets merged

**Comment by zhouzaida** [comment]
thanks
