### ISSUE TITLE
my codebase is deleted when I set the path as my codebase directory

### ISSUE THREAD

**Issue by zhouzaida** [iterative/dvclive#102]
When I set the path as my codebase directory, a terrible thing happened. My codebase was deleted. 

https://github.com/iterative/dvclive/blob/8b260ae19a834b693ca8853b6d12140ec695effc/dvclive/metrics.py#L43

**Comment by pared** [comment]
@zhouzaida sorry to hear that, did you managed to recover your project?

How did you called `init`? 
`dvclive.init(".")`?

This is a tricky one. On one hand, we allow such situation to happen. On the other, if we will start throwing errors/prompting on existing directory, the library will become unusable.

Maybe we should check if user does not call `init` for `cwd`? That would prevent such situation from happening.

**Comment by zhouzaida** [comment]
dvclive.init(path='my-codebase-directory

The deleted codebase is just a dummy codebase

**Comment by pared** [comment]
@zhouzaida 
So the path that we are specifiying will be a directory where `dvclive` will be writing the files with the metrics. It is supposed to be previously unsued directory eg (`dvclive.init("{your_project_path}/project-metrics")`). The removal of target dir is happening because user might want to rerun the code. In that case we need to make sure we do not have previous trainings results there. Hence the deletion and need to initialize it in its own directory. You can also not provide `path` and `dvclive` will write the metrics into `{your_project_path}/dvclive`.

**Comment by daavoo** [comment]
Given that `The removal of target dir is happening because user might want to rerun the code` maybe the call to `shutil.rmtree` could be conditioned on whether `self.dir` is a `dvclive` directory or not. 

For example, we could check if `self.dir` only contains `.tsv` files before running `shutil.rmtree` and raise an Exception in case the provided `path` contains other files

**Comment by dberenbaum** [comment]
Why does the entire directory need to be deleted instead of just the individual files that are being written?

Also, what if I want to resume an existing experiment?

**Comment by zhouzaida** [comment]
> Why does the entire directory need to be deleted instead of just the individual files that are being written?
> 
> Also, what if I want to resume an existing experiment?

https://github.com/iterative/dvclive/blob/8b260ae19a834b693ca8853b6d12140ec695effc/dvclive/metrics.py#L35

resuming an existing experiment is supported.

**Comment by daavoo** [comment]
> Why does the entire directory need to be deleted instead of just the individual files that are being written?

Good question, the logic of deleting `just the individual files that are being written` could be moved to `dvclive.log` instead. 

However, maybe (I don't really know) one reason for removing the entire directory would be that if the metrics being logged change from one experiment to other, it can be misleading to have existing metric files (`.tsv`) unrelated with the current experiment?

**Comment by pared** [comment]
> Why does the entire directory need to be deleted instead of just the individual files that are being written?

My thinking was that when we are running given training script we want to have consistient and reproducible results, so it would make sens to have single output directory for given "training". That makes sure that given results belong to particular run. Having said so it might be some dvc concepts leaking into `dvclive`. @dberenbaum do you think we should allow mixing the results with other files contained in given directory?

**Comment by dberenbaum** [comment]
I think it makes sense the way it is for now. Someone might want to put all of their tsv outputs into one directory, which could be a mix of dvclive files and others, but we can revisit if that hypothetical becomes more of a real concern.

**Comment by daavoo** [comment]
> I think it makes sense the way it is for now. Someone might want to put all of their tsv outputs into one directory, which could be a mix of dvclive files and others, but we can revisit if that hypothetical becomes more of a real concern.

Not sure how hacky would be this option but how about updating `dvclive` to use `.dvclive.tsv` (or something like that) as suffix for the *plot metrics* files? 

If we add something like that, we could update the "clean up" metrics to ensure that just the `dvclive` related files are removed (summary and html paths are already tracked and cleaned up separately: https://github.com/iterative/dvclive/pull/96). This could allow to more flexible `path` selection and avoid accidental removals like the one reported in this issue

**Comment by pared** [comment]
@daavoo this sounds good, but we need to remember that it will be showing up in a `dvc plots` results. I am not sure that this particular use case is that important - using `dvclive` and mixing different outputs will definintely result in problems when one uses `dvc`. Maybe we should make it more clear in docs that `init` dir should be reserved for `dvclive` outputs only?

**Comment by daavoo** [comment]
> @daavoo this sounds good, but we need to remember that it will be showing up in a `dvc plots` results. I am not sure that this particular use case is that important - using `dvclive` and mixing different outputs will definintely result in problems when one uses `dvc`. Maybe we should make it more clear in docs that `init` dir should be reserved for `dvclive` outputs only?

I've tried adding the `.dvclive.tsv` suffix and it is not showing on `dvc plots` (it uses the name of the column header). I think that, as there is not real impact beyond ensuring we don't accidentally delete other user files, we could add that change.

I agree with the need for a clarification in the docs, could be added in addition to the change.

**Comment by dberenbaum** [comment]
I already don't love that `dvclive` is in the directory and summary paths by default, since it makes the output paths less generically useful, but at least those can be changed. If we take the `.dvclive.tsv` approach, it makes these all look like special `dvclive` files instead of regular metric logs that happen to have been written using `dvclive`.

@daavoo Do you see a need to have a directory with mixed `dvclive` and other outputs?

**Comment by dberenbaum** [comment]
> My thinking was that when we are running given training script we want to have consistient and reproducible results, so it would make sens to have single output directory for given "training". That makes sure that given results belong to particular run. Having said so it might be some dvc concepts leaking into `dvclive`. @dberenbaum do you think we should allow mixing the results with other files contained in given directory?

Also, the idea that dvc needs to delete all existing files before running is kind of an outdated one. We may stop doing that in dvc, in which case we might want to rethink the approach here. I don't think it's a high priority to change the behavior in `dvclive` now.

**Comment by daavoo** [comment]
> I already don't love that `dvclive` is in the directory and summary paths by default, since it makes the output paths less generically useful, but at least those can be changed. If we take the `.dvclive.tsv` approach, it makes these all look like special `dvclive` files instead of regular metric logs that happen to have been written using `dvclive`.
> 
> @daavoo Do you see a need to have a directory with mixed `dvclive` and other outputs?

I'm not sure. The scope of the related P.R. was just to prevent users from accidentally deleting a full directory. I think that we can just remove `.tsv` files (https://github.com/iterative/dvclive/pull/122#issuecomment-884072343) as a compromise. This would remove the `.dvclive` prefix and at make the cleanup a little safer for the user.

**Comment by dberenbaum** [comment]
That makes sense. It's probably better to not be overly aggressive with deletion.

I'd still consider waiting or coordinating with plans for future DVC behavior to try to be consistent. Cc @efiop any thoughts?

**Comment by efiop** [comment]
@dberenbaum Have to note that in dvc we do that while checking that the files we are deleting are present in the cache, which is only slightly better. But I agree that we could be smarter about that in dvc (e.g. by checking mtime and maybe warning the user that it looks like his outputs didn't come from his stage or smth like that) or maybe backing up existing outputs into a temp location (e.g. data -> data.old) so it is recoverable. The latter one could be done by dvclive right now, to mitigate this issue while still avoiding promts and stuff from dvc.
