### ISSUE TITLE
Add a way to save models

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvclive#105]
Integrations should include an option to save model to file. See #69.

---

Edited with tasklist:

- [x]  Keras #69 
- [x] #109
- [x] #110

**Comment by pared** [comment]
If we decide we want to control it on integration-level #69 can be merged as is.

**Comment by dberenbaum** [comment]
Do you think it's important to be consistent across integrations so that we don't have to document what each one does individually? Also, might it be important to have a generic method in case we have some change we want to make across integrations (for example, add some logic to track the output if inside a dvc project)?

**Comment by dberenbaum** [comment]
Looking back at #69, I don't think it needs to be in `dvclive.init()`, and I think it could be merged as is, although we should also add similar functionality for xgboost. 

I was thinking we might need something like `dvclive.save_model(save_func, model_file)` if we have some generic logic we need to apply, but we can add that later if needed.

**Comment by pared** [comment]
> dvclive.save_model(save_func, model_file)

If user can register own callback, that would take a lot of work out of our way.  Not sure whether that feature would be used a lot. If one needs to write saving funciton anyway, why spend even more time reading how to register it in DVCLive and how it would be handled inside, instead of manually calling that every now and then.

**Comment by pared** [comment]
Looking at @daavoo's [comment](https://github.com/iterative/dvclive/pull/69#issuecomment-878124882) we can see that it would be easier for us to require user to provide saving method. But my original concern remains: will it be used at all?

**Comment by dberenbaum** [comment]
> will it be used at all?

`DvcLiveCallback(model_file="output_model.h5"` seems useful since it saves users from a separate call or from remembering how to save in keras or other frameworks.

I agree that `dvclive.save_model(save_func, model_file)` does not seem particularly useful. In the future, we might try to do more with dvclive, like make it add the model file as a dvc-tracked output. In that case, we might need a feature like this (or a similar decorator) to implement across the various integrations, but we can worry about it when we need it.

**Comment by daavoo** [comment]
I reached a similar conclusion when reviewing how to add this functionality to both `keras` and `MMCV` integrations:

https://github.com/iterative/dvclive/pull/69#issuecomment-879778857
https://github.com/iterative/dvclive/issues/110#issuecomment-879798088

With the current set of `dvclive` features I don't really see why an user would choose to use the "native model saving" logic of our integrations.

Looking at what other *ML Loggers* do, I kind of like what [`wandb` does in `pytorch-lighting`](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/loggers/wandb.py#L249) which is searching for the model already saved by other callback although this might not apply to all *ML Frameworks*.

In addition, other *ML Loggers* tend to use the saved model with some `log_artifact` method and I'm not sure to what would this be translated in `dvc<>dvclive` terms. Maybe it is what we already do with `checkpoints`? Or a potential new feature taking care of calling `dvc add`?

**Comment by dberenbaum** [comment]
> In addition, other _ML Loggers_ tend to use the saved model with some `log_artifact` method and I'm not sure to what would this be translated in `dvc<>dvclive` terms. Maybe it is what we already do with `checkpoints`? Or a potential new feature taking care of calling `dvc add`?

If using dvc checkpoints, then yes, the model output is already tracked at each step, although this requires some manual stage setup that dvclive might be able to help make easier. Having dvclive take care of calling `dvc add` or otherwise ensuring that the output is tracked by dvc and not git would be nice.

**Comment by daavoo** [comment]
All existing integrations already support saving models so I'm closing this issue.

We can now start requiring model saving capabilities to new integrations.
Future improvements regarding saving models could be discussed in a separate issue as they come.
