### ISSUE TITLE
Save model in `MMCV`

### ISSUE THREAD

**Issue by daavoo** [iterative/dvclive#110]

**Comment by daavoo** [comment]
Similar concerns to the ones described in https://github.com/iterative/dvclive/pull/69#issuecomment-879778857

`MMCV` already has a [`CheckpointHook`](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/hooks/checkpoint.py#L9) and all "downstream" repositories are configured to use it (i.e. [mmdetection](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/apis/train.py#L126)).

What would be the benefits of adding this functionality to [`DvcliveLoggerHook`](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/hooks/logger/dvclive.py)?? 

In the case of `MMCV` this benefit mentioned in https://github.com/iterative/dvclive/pull/69#issuecomment-811393960:

>Also, you can mix up the order if you separate them that will create checkpoints with previous models - another place when user can make a mistake.

Doesn't really apply because MMCV already has a default priority for calling hooks that prevent this:

https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/base_runner.py#L526

**Comment by dberenbaum** [comment]
> Doesn't really apply because MMCV already has a default priority for calling hooks that prevent this:

Oooh, that's nice. Do you know the order of hooks for keras or others?

**Comment by daavoo** [comment]
> Oooh, that's nice. Do you know the order of hooks for keras or others?

It appears to just follow the order of the list passed to `model.fit`:

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/callbacks.py#L434
