### ISSUE TITLE
docs: Extend auto-linker to work with `dvclive` API

### ISSUE THREAD

**Issue by daavoo** [iterative/dvclive#114]
future improvement: we should create a ticket or improve auto-linker, to keep text clean from these internal links like we do in DVC API reference

_Originally posted by @shcheklein in https://github.com/iterative/dvc.org/pull/2632#discussion_r670704982_

**Comment by jorgeorpinel** [comment]
> improve auto-linker

Meaning in the `dvc.org` engine, right?

**Comment by daavoo** [comment]
> > improve auto-linker
> 
> Meaning in the `dvc.org` engine, right?

Yep

**Comment by jorgeorpinel** [comment]
Are we planning to host DVCLive docs in dvc.org long-term?

**Comment by shcheklein** [comment]
> Are we planning to host DVCLive docs in dvc.org long-term?

No the near future plans to move it. Also, we would need this anyway, only base part of the link will be changing.

**Comment by shcheklein** [comment]
Also, I think these issues are at least of the same importance as writing docs - we should pay attention to automation, dev (writers) experience, keep MD files as clean and simple as possible.

**Comment by jorgeorpinel** [comment]
OK. Also keep in mind we can use reference links like

```md
Some text with [`dvclive.init()`] link... (can be repeated)

[`dvclive.init()`]: /doc/dvclive/api-reference/init
```

If we want to do something about it without waiting for the engine change.
