### ISSUE TITLE
integrations: LightGBM

### ISSUE THREAD

**Issue by daavoo** [iterative/dvclive#132]
It would be nice to have a `dvclive` integration with [LightGBM](https://lightgbm.readthedocs.io/en/latest/).

> LightGBM is a gradient boosting framework that uses tree based learning algorithms.

Example of custom callback:

https://github.com/microsoft/LightGBM/blob/master/examples/python-guide/advanced_example.py#L199

We would maintain the implementation in the DVCLive repository.

- [ ] Add new callback to DVCLive
- [ ] Update docs in [dvc.org](https://github.com/iterative/dvc.org)

**Comment by pacifikus** [comment]
Hello, @daavoo 
I've added a callback for lgbm, where can I place the docs update? I see folder dvc.org/content/docs/dvclive/user-guide/ml-frameworks in one branch on review, is it ok for PR?

**Comment by daavoo** [comment]
> Hello, @daavoo
> I've added a callback for lgbm, where can I place the docs update? I see folder dvc.org/content/docs/dvclive/user-guide/ml-frameworks in one branch on review, is it ok for PR?

Hi! 

The User Guide, where integrations will be documented, is still a work in progress so for now just don't worry about it and I will take care of adding LightGBM docs once the P.R. gets merged.
