### ISSUE TITLE
logger: log to summary first, then to logs

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvclive#145]
Extracted from https://github.com/iterative/dvclive/pull/142#pullrequestreview-738942719.

Would summary -> tsv be more helpful (this would obviously require summary to always exist)? It's more intuitive to me (and follows the internal logic of MetricLogger._metrics) to gather all metrics for a step and then append to metrics logs. It also enables no-step scenarios like classical ML algorithms by logging the summary without ever creating the tsv files.

**Comment by daavoo** [comment]
Related: https://github.com/iterative/dvclive/pull/157#discussion_r706467734

**Comment by daavoo** [comment]
Coming from #157 , looks like instead of switching `tsv` -> `summary` order would be better to just do `tsv` and `summary` in the same place (`dvclive.log`)

**Comment by dberenbaum** [comment]
From https://github.com/iterative/dvclive/pull/157#discussion_r708452879:

> @dberenbaum @pared even if we consider thesummary behavior fixed (by moving it to log), it doesn't feel like there is a way to fulfill the 3 points listed above when considering html and checkpoints.

This might not be an issue since I think a final checkpoint is implicitly added if anything has changed since the last checkpoint.

**Comment by pared** [comment]
@dberenbaum I modified the discussion title to make it  clearer
