### ISSUE TITLE
`dvclive.log`: Support images

### ISSUE THREAD

**Issue by daavoo** [iterative/dvclive#150]
Now that dvc has [support for logging images](https://github.com/iterative/dvc/pull/6431), it makes sense to also add support on the `dvclive` side.

A few questions arise:

## `dvclive.log` or `dvclive.log_image`

Should the existing `dvclive.log` method be extended to accept a new input type (Image-like) or should we add a new separate method ? 

For reference:

- wandb has a single [`log` method](https://docs.wandb.ai/guides/track/log) that handles every type.
- CometML has a separate [`log_image`](https://www.comet.ml/docs/python-sdk/APIExperiment/#apiexperimentlog_image)
- MLFlow uses a separate general method [`log_artifact`](https://www.mlflow.org/docs/latest/python_api/mlflow.html#mlflow.log_artifact)
- Neptune has a single [`log` method](https://docs.neptune.ai/api-reference/field-types#log-2) that can receive images (`File.as_image`).

## Valid inputs

What kind of objects should be accepted to log as images? How would be handled by `dvclive`?

On the dvc side, the only condition is that the image is stored in a [valid format ](https://github.com/iterative/dvc/blob/master/dvc/render/image.py#L61). 

On `dvclive` we should consider what we will accept as inputs and how to handle them. 

The more common Image-like objects I can think of are:

- 2D/3D array/tensor (i.e. Numpy, PyTorch) 
- Pillow Image
- Matplotlib Figure

In addition we need to consider if we want to also accept a string indicating a path to an existing image file (i.e. `dvclive.log_image("foo.png")`), for cases where the user takes care of saving the image by itself.

**Comment by daavoo** [comment]
> Should the existing dvclive.log method be extended to accept a new input type (Image-like) or should we add a new separate method?

I'm more inclined to extend `dvclive.log` to keep the API as simple as possible, although I have no strong preference.

> What kind of objects should be accepted to log as images? How would be handled by dvclive?

I think that we should use Pillow internally for saving the images and just accept anything that can be converted to a Pillow image (like the list above).

Not sure if we should consider an already saved image a valid input, as it might get tricky regarding how DVC would handle it in terms of caching (i.e. should we copy or move it in order to let DVC handle the output as configured in the `dvc.yaml`)

**Comment by daavoo** [comment]
cc @dberenbaum @pared

**Comment by pared** [comment]
I don't see a reason why would we need separate methods. It seems to me that in most cases we could determine the way of storing the object by its type. 

We need to remember that we might not have the necessary tools for that (if we have vanilla `dvclive` it might be hard to determine whether a given object is pytorch's tensor). 

> I think that we should use Pillow internally for saving the images and just accept anything that can be converted to a Pillow image (like the list above).

I am fine with using Pillow, though we need to decide whether we add a dependency to `dvclive` or create a new setup option `dvclive[images]`.

The biggest problem I see is integration with DVC. This will heavily depend on how we deal with iterative/dvc#5980 - and actually, we might need to do it on `dvc` side first, and later adjust here.

**Comment by daavoo** [comment]
> I don't see a reason why would we need separate methods. It seems to me that in most cases we could determine the way of storing the object by its type.

Agree 

> We need to remember that we might not have the necessary tools for that (if we have vanilla `dvclive` it might be hard to determine whether a given object is pytorch's tensor).

PyTorch won't be really needed for the check, I think. You can just implement the check parsing the strings in `X.__class__` and add lazy imports required for conversion in a separate "convert from PyTorch" function.

> I am fine with using Pillow, though we need to decide whether we add a dependency to `dvclive` or create a new setup option `dvclive[images]`.

Feels to me that Images should be a first-class citizen and hence Pillow (or whatever) a required dependency. No strong opinion, though.

> The biggest problem I see is integration with DVC. This will heavily depend on how we deal with [iterative/dvc#5980](https://github.com/iterative/dvc/discussions/5980) - and actually, we might need to do it on `dvc` side first, and later adjust here.

@pared Do you mean that the existing `image` support might change? As of today, DVCLive would only need to take care of saving images in the correct folder, right?

**Comment by pared** [comment]
> @pared Do you mean that the existing image support might change? As of today, DVCLive would only need to take care of saving images in the correct folder, right?

My concern is how should we treat logged images - when we are logging int/float values we expect that the user will run `dvc plot` on this file. Each step is saved as entry in tsv file. How do we do that in the case of images?  save it under `images/{image_metric_name}/{step}`? Then how do we display it using DVC? We are unable to compare different images on the same commit.

**Comment by dberenbaum** [comment]
Related to #82.

**Comment by dberenbaum** [comment]
@daavoo What would you expect to log here and what output would be helpful? Would you want to compare all steps across time? Would you want this logged like live metrics in the html that get updated at each step?

**Comment by daavoo** [comment]
@dberenbaum I accidentally edited your comment instead of quote reply 😅 

> What would you expect to log here and what output would be helpful? 

I would like to be able to pass any Image-like object (i.e. the list in the description) to `dvclive.log` and a `filename`. I would expect `dvclive` to take care of saving the image in the right format and path (i.e. `{dvclive.images_path}/{filename}`).

As this method won't be probably called automatically by the integrations (unlike how scalars are automatically logged) I would expect to have the flexibility to configure the behavior of `dvc plots` based on filename conventions (see below).

> Would you want to compare all steps across time? 

Yes. Ideally, a slider like what you get in TensorBoard would be ideal:

![TensorBoard](https://user-images.githubusercontent.com/12677733/133120329-8617f762-17ad-445d-b94f-b586ab709a21.gif)


I realize this is not feasible right now so more realistically I would expect images logged in a subdir (i.e. `{dvclive.images_path}/subdir/*.png` to be grouped together in the same `html` component (`<div>`?) when `dvc plots` is called.

> Would you want this logged like live metrics in the html that get updated at each step?

Yes. I would expect images to be treated just like the `.tsv` plots.

**Comment by dberenbaum** [comment]
> I realize this is not feasible right now so more realistically I would expect images logged in a subdir (i.e. `{dvclive.images_path}/subdir/*.png` to be grouped together in the same `html` component (`<div>`?) when `dvc plots` is called.

DVC issue for this: https://github.com/iterative/dvc/issues/6603

> Ideally, a slider like what you get in TensorBoard would be ideal:

Is it worth providing an option to integrate with TensorBoard to enable this (see https://github.com/iterative/dvclive/issues/66)? It seems easier than adding sliders into DVC HTML, and users might prefer this if they are already familiar with TensorBoard.
