### ISSUE TITLE
Add `dvclive.set_step`

### ISSUE THREAD

**Issue by daavoo** [iterative/dvclive#154]
From #144. Remove `step` from `dvclive.log` level and add a new method `dvclive.set_step` for enabling "custom step" behavior.

**Comment by pared** [comment]
I know its getting boring,  but maybe we should also add `get_step`? :D (vide https://github.com/iterative/dvclive/pull/142#discussion_r702908276 discussion) Now it would make more sense to have both getter and setter

**Comment by dberenbaum** [comment]
Wish I had seen the comment above before adding more to that thread 🤣 .
