### ISSUE TITLE
Public methods vs MetricsLogger instantiation

### ISSUE THREAD

**Issue by daavoo** [iterative/dvclive#159]
Not sure if this belongs in this issue, but what is the advantage of `dvclive.init()` over `logger = dvclive.MetricsLogger()` as the canonical workflow? Explicitly calling `MetricsLogger` seems more transparent, removes an extra layer of abstraction, and makes it easier to manage multiple loggers.

_Originally posted by @dberenbaum in https://github.com/iterative/dvclive/issues/156#issuecomment-916874901_

**Comment by pared** [comment]
Public functions require us to handle logger object instantiation. If we move this responsibility to users we effectively remove the need to handle multi-threaded use cases like #36.
