### ISSUE TITLE
html: render without dvc integration?

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvclive#163]
Should HTML output be tied to DVC integration? Features like #82 and #150 may depend on the HTML report to show the logged data/images. DVCLive will be pretty limited without DVC if we continue in the current direction.

Options to consider:
1. Continue requiring DVC for HTML output, noting the limitations of using without DVC.
2. Continue requiring DVC for HTML output and stop support for non-DVC scenarios.
3. Refactor to remove HTML plotting/rendering from DVC and keep it as a separate library.
4. Refactor to remove HTML plotting/rendering from DVC and integrate it into DVCLive.
5. Build DVCLive-specific HTML rendering/visualization.

**Comment by daavoo** [comment]
When considering only how this affects DVCLive, would this kind of concern be covered by https://github.com/iterative/dvclive/issues/61 ? Making `dvc` just one of different "plotting" backends would solve the `pretty limited without DVC`, I think.

However it feels like implementing some of that options would have impact beyond DVCLive and that's what we are discussing here

**Comment by dberenbaum** [comment]
> > Refactor to remove HTML plotting/rendering from DVC and keep it as a separate library.
> 
> This is already happening on DVC side - current HTML generation implementation requires DVC only to load the templates, besides that the renderers can happily live alone. I guess we can consider making a package out of it.

From recent comments in https://github.com/iterative/dvclive/pull/166#issuecomment-925270199 and https://github.com/iterative/dvc.org/pull/2839#discussion_r714264722, the `dvc plots diff` output for images looks similar to what might be wanted for dvclive image support (a directory with a `{step}_file.png` for each step). I wonder if abstracting/packaging the HTML rendering would enable flexibility to show a directory of images the same way in dvclive that they are shown in `dvc plots diff`.

**Comment by pared** [comment]
@dberenbaum yep it woul,

Rendering method of DVCLive just requires templates and proper data structure, a dict as follows:

```
{
"revision":
  {
  "filename":
    {
      "data" : {vega content or binary data for image}
    }
  }
}
```
We could just build the dict on dvclive side and pass it to rendering function.
If we are to extract rendering to separate package we would probably need some renaming (like not relying on `revision`, as its git concept, but maybe `version`) but those are minor things that are not essential to make it work.

**Comment by daavoo** [comment]
Closing in favor of #213
