### ISSUE TITLE
Extra set of directories created while using live option

### ISSUE THREAD

**Issue by dragarok** [iterative/dvclive#169]
Python version: 3.8.5
DVC version: 2.7.4 (pip)
DVC live version: 0.2.3

In using dvc live option, it creates extra set of directories when called from within dvc.yaml's current working directory. This is creating issue while running command "dvc push" which results in error saying the directory couldn't be found. 
In my case, it is train_metric.

[Link to dvc.yaml](https://github.com/dragarok/ML_Workflow_Demo/blob/f67dec57d27397e78bfbe72bc6fa3b12a2cc0fe8/ContinuousML/NQ_DR_4_10_20_Ideal_27/2_Training_Workflow/dvc.yaml)

[Link to folder](https://github.com/dragarok/ML_Workflow_Demo/tree/f67dec57d27397e78bfbe72bc6fa3b12a2cc0fe8/ContinuousML/NQ_DR_4_10_20_Ideal_27/2_Training_Workflow)

**Comment by daavoo** [comment]
Looking into this, thanks for reporting @dragarok

**Comment by daavoo** [comment]
Issue was on the DVC side, should be fixed by https://github.com/iterative/dvc/pull/6740
