### ISSUE TITLE
`dvc`: Absolute path for `DVCLIVE_PATH` env var.

### ISSUE THREAD

**Issue by daavoo** [iterative/dvclive#171]
I think we should keep the path in envvar in an absolute form in `DVCLIVE_PATH`. Otherwise, the user's script could change the working directory similar to following:
```suggestion
    (tmp_dir / "subdir").gen("train.py", "import os\nos.chdir('..')\n" + LIVE_SCRIPT)
```

_Originally posted by @skshetry in https://github.com/iterative/dvc/pull/6740#discussion_r721960389_

**Comment by skshetry** [comment]
Isn't this a `dvc`'s issue where it sets `DVCLIVE_PATH` to be a relative path (even before your last PR)?

https://github.com/iterative/dvc/blob/16f404b16a50/dvc/stage/__init__.py#L276

**Comment by daavoo** [comment]
> Isn't this a `dvc`'s issue where it sets `DVCLIVE_PATH` to be a relative path (even before your last PR)?

Yep but I kind of track any DVCLive related issues on this repo regardless of whether the changes should go to DVC or this repo
