### ISSUE TITLE
`step`: Remove methods in favor of `@property`.

### ISSUE THREAD

**Issue by daavoo** [iterative/dvclive#172]
Now that there are no public methods, some of the `Live` methods (`get_step`, `set_step`, `next_step`) feel redundant as they could be replaced with common python property syntax:

`Live.get_step()` -> `Live.step`
`Live.set_step(X)` -> `Live.step = X`
`Live.next_step()` -> `Live.step += 1`

**Comment by dberenbaum** [comment]
Could support both, but maybe that goes against the "canonical workflow."

**Comment by dberenbaum** [comment]
Looking at the docs, this would do a lot to simplify the API.

**Comment by dberenbaum** [comment]
> Could support both, but maybe that goes against the "canonical workflow."

Also could deprecate by keeping but not documenting the step methods.
