### ISSUE TITLE
`html`: nest inside dvclive dir

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvclive#195]
See the complaint in https://discord.com/channels/485586884165107732/485596304961962003/915439735256801352, which more generally complains of too many dvc-related paths, but specifically calls out `dvclive_dvc_plots`. While they can configure the `dvclive` part, they will still have a path like `{dir}_dvc_plots`. It would be nice to nest the plots directory inside `{dir}` and not have to include `dvc` anywhere in the path since these are supposed to be general purpose outputs.

**Comment by daavoo** [comment]
This has to be solved on DVC side, unless/until https://github.com/iterative/dvc/issues/6944 is implemented

**Comment by daavoo** [comment]
The problem with the existing DVC integration would be that anything inside `{dvclive.dir}` is tracked equally by DVC

**Comment by dberenbaum** [comment]
Even `{dir}_plots` seems nicer than `{dir}_dvc_plots`. What do you think?

 > This has to be solved on DVC side

True. We can transfer or keep discussion here and transfer/open a new issue once there is a decision.
