### ISSUE TITLE
`dvc`: Add option to disable automatic open

### ISSUE THREAD

**Issue by daavoo** [iterative/dvclive#201]
Users might want to have html generation without automatically open the browser.

**Comment by shcheklein** [comment]
Question, what was the initial motivation to make this behavior default? It feels a bit too "intrusive" since it changes my context automatically.

**Comment by shcheklein** [comment]
And a bit more context, having this option is critical for VS Code. And probably we'll want to have a way to override the default behavior (e.g. env var).

**Comment by daavoo** [comment]
> Question, what was the initial motivation to make this behavior default? It feels a bit too "intrusive" since it changes my context automatically.

No strong motivation. We decided to make it default and wait for users asking for an option to opt out.
My personal bias was that if you generate the live HTML it is to look at it during training (otherwise you could just use DVC plots). I was aware it could be a too aggressive default.

 > And a bit more context, having this option is critical for VS Code. And probably we'll want to have a way to override the default behavior (e.g. env var).

I think HTML generation doesn't make sense for users of the VSCode extension (live plots of extension replace it). Based on that assumption, VSCode could be already re-using the existing env var `DVCLIVE_HTML` (it already defaults to false) to disable HTML generation at all.  @shcheklein @iterative/vs-code ?

Regardless of that env var, I would add a specific env var for the web browser open.
