### ISSUE TITLE
`log`: Verbose mode

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvclive#206]
It would be nice to have a way to see what dvclive is doing instead of having it operate silently, so that stdout/loggers could optionally have info about when dvclive calls are made and what they are logging. This would be especially helpful in debugging.

**Comment by daavoo** [comment]
Outside of debugging, one potential issue could be in integrations, where dvclive logs could interfere with the ML Framework output (https://github.com/iterative/dvclive/issues/177)
