### ISSUE TITLE
integrations: Add `live` kwarg to callbacks

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvclive#207]
Instead of assuming a new `Live` instance in callbacks, should it allow for `DvcLiveCallback(live=myliveinstance)`? This could better support the workflow mentioned in https://github.com/iterative/dvc.org/issues/2773.

For example:

```
from dvclive import Live
from dvclive.keras import DvcLiveCallback

live = Live("custom_path")
model.fit(callbacks=[DvcLiveCallback(live=live)])
```

**Comment by daavoo** [comment]
> This could better support the workflow mentioned in iterative/dvc.org#2773.

Not sure what workflow do you refer to 😅 

What would be the benefits of that approach? or What are the limitations of the current one?

**Comment by dberenbaum** [comment]
It's not high priority, and it's not intending to replace the current approach.

In iterative/dvc.org#2773, it was unclear whether to instantiate the `Live` instance before using the callback.

For example:

```
live = Live("custom_path")
model.fit(callbacks=[DvcLiveCallback()])
```

The outputs will be in `dvclive` instead of 'custom_path`, which might be unexpected. If they want to get the expected behavior, they will have to rewrite their code like:

```
model.fit(callbacks=[DvcLiveCallback(path="custom_path")])
```

An alternative could be to also allow:

```
live = Live("custom_path")
model.fit(callbacks=[DvcLiveCallback(live=live)])
```

If both `live` and other kwargs like `path` are provided, an error could be thrown. It just gives users another way to fix the problem in case it's not obvious to drop the instantiation.

I will close it for now. If anyone encounters confusion, we can revisit.
