### ISSUE TITLE
live: Deprecate summary

### ISSUE THREAD

**Issue by daavoo** [iterative/dvclive#211]
At what point do we make the summary required? It seems it's taking substantial effort to keep working around it being optional.

_Originally posted by @dberenbaum in https://github.com/iterative/dvclive/issues/210#issuecomment-1023609030_

**Comment by daavoo** [comment]
Unless I'm missing something, I can't really think of a strong reason to keep it optional.

**Comment by dberenbaum** [comment]
Yeah, it seems to come up frequently. I'd prefer to make it required instead of continuing to add special logic for `summary=False`.

**Comment by shcheklein** [comment]
Just for the context - are we also getting rid of it in DVC (dvc.yaml has that option, right?)?

**Comment by daavoo** [comment]
> Just for the context - are we also getting rid of it in DVC (dvc.yaml has that option, right?)?

The plan is to deprecate the entire `live` section after #213

**Comment by dberenbaum** [comment]
Good point, @shcheklein. In the meantime, we can document that `summary: false`/`--live-no-summary` will be ignored in `dvclive>=0.6.0`.
