### ISSUE TITLE
`log_image`: Support logging `matplotlib` figures.

### ISSUE THREAD

**Issue by daavoo** [iterative/dvclive#224]
`log_image` currently supports `numpy` and `PIL` as inputs. It would be nice to also support `matplotlib` figures

**Comment by dberenbaum** [comment]
This would be nice to add in https://github.com/iterative/example-repos-dev/blob/cfa4ca4d4097cab26b2921026dfb3a41c70fadaf/example-get-started/code/src/evaluate.py#L72
