### ISSUE TITLE
`report`: how to make report in no-step scenarios

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvclive#231]
> It seems odd to pass Live(report="html") in no-step scenarios and have that kwarg do nothing. 

Not sure if it should be part of this PR, but currently, I can use the `live` section in `dvc.yaml` to get a report even in no-step scenarios, but it doesn't seem like it's possible without the `live` section. Is there some way to still generate the report by default?

_Originally posted by @dberenbaum in https://github.com/iterative/dvclive/pull/227#discussion_r839895032_

**Comment by dberenbaum** [comment]
>  Is there some way to still generate the report by default?

When using the `live` section in no-step scenario, the report gets generated by the monitor task after the stage has ended. 
Any implementation on DVCLive side would behave differently, as the `Live` object doesn't have info of when the "stage" has ended (the closest would be to implement the logic in `__del__`) .
IMO would be better to document `Live.make_report()` and emphasize it's usage for non step scenarios

_Originally posted by @daavoo in https://github.com/iterative/dvclive/pull/227#discussion_r840416323_

**Comment by dberenbaum** [comment]
It seems clunky to me to have the report generated automatically in step scenarios but not in no-step scenarios.

Possible ways to make the experiences consistent:

1. Never auto-generate reports and require users to call `Live.make_report()` after every `Live.next_step()` call. This fits with the explicit canonical workflow emphasized in #156, but it's starting to get to be a lot of methods that need to be called for what used to be possible with just `dvclive.log()`.
2. Invoke `make_report` whenever `Live.log()` is called and `Live._step is None`. We already have some special logic for how to log things in no-step scenarios, so this might not be too different, although partial reports may be generated, which might seem awkward. It also could make it more complicated to determine when to send reports for things like #91.

Would either of these improve the experience? Are there other ideas?

**Comment by daavoo** [comment]
> Would either of these improve the experience? Are there other ideas?

I would like to go with `1`.

> it's starting to get to be a lot of methods that need to be called for what used to be possible with just `dvclive.log()`.

I think that the main DVCLive use case would be based on integrations for step scenarios. In that use case, we will still be creating the report "automatically" by calling `make_report` at the end of each epoch.

For scenarios where users need to manually call the API, my personal preference is to have explicit methods, each one doing a single thing. 

We would have 3 methods for 3 different actions (logging data, updating step, generating report). IMO opinion this is a better API than having a method called `log` but having to explain that it also does 3 other things (counting checkpoints).
