### ISSUE TITLE
`log`: optimize dumping to files

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvclive#238]
Seems odd to do this. If there are multiple things to log per iteration, you dump multiple times?

- Seems better to dump only on `next_step()`
- Could also make configurable default `log(..., write_summary=False)`
- Could make `next_step()` internally use `log("step", ..., write_summary=True)`

I don't quite follow the wording in #145 but from what I can tell it seems identical to this issue (#232) so shouldn't have been closed?

_Originally posted by @casperdcl in https://github.com/iterative/dvclive/issues/232#issuecomment-1087252929_

**Comment by daavoo** [comment]
We could take https://github.com/iterative/dvclive/pull/338 one **step** further and remove implicit `make_summary` calls. 

API would look a little polluted but I think it is still not too bad and explicit:

```
for step in range(2):
    live.log_metric("foo", 1)
    live.log_metric("bar", 2)
    live.make_summary()
    live.next_step()
```

Considering callbacks as the main entry point would make the change more like an internal detail

**Comment by shcheklein** [comment]
How about `live.dump`? (and autodump mode)? 

Dumping on the `next_step` makes sense also.

**Comment by dberenbaum** [comment]
I don't see this actually causing problems now, so not sure it's worth trying to address if it's about optimization, but if it cleans up the API, I'm open to it.

@daavoo Your idea would mean either `make_summary` or some other method should be called in no-step scenarios, right? That might be okay, just want to clarify the tradeoff.

As an alternative, the idea of #145 is still not really implemented IMO. I expected it to look like:
1. `log_metric` updates `metrics.json`, which is not really a summary but instead the output of `log_metric` (none of the other log methods generate step-specific output now).
2. A new method like `make_hist` generates the tsv file, and this could be called during `next_step`.

That workflow would have the tradeoff that the last step might not get logged to the tsv file.

In either case, if we have a context manager and recommend that in 1.0, it can solve these tradeoffs if additional methods are called on exit.

**Comment by casperdcl** [comment]
for me it's about:

1. intuitive (and clean) API
2. configurability (e.g. log every N steps)

**Comment by dberenbaum** [comment]
Discussed with @daavoo and decided that:

1. It's fine to only call `make_summary` at the end of each step.
2. We should still call it within `next_step` or have some method that can call this along with the methods removed in https://github.com/iterative/dvclive/pull/338 so that non-callback users don't need to manually call something like:

```
for step in range(2):
    live.log_metric("foo", 1)
    live.log_metric("bar", 2)
    live.make_summary()
    live.make_checkpoint()
    live.make_report()
    live.next_step()
```
