### ISSUE TITLE
`auto_open`: how to handle it

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvclive#241]
During discussion with @mattseddon, it came up that changing `auto_open` default to `True` broke the VS Code extension. This has since been reverted in #240, but there are still questions about how to prevent this behavior and when to automatically open the report.

Some issues with `auto_open` behavior:
* How do we ensure this doesn't happen again in VS Code or in other scenarios like CI where it's not needed? Should we have a way to override it through something like an environment variable, or always respect whether dvclive is being run in a tty?
* If we will have non-html report formats, will `auto_open` make sense?
* Should there be an explicit method to open the report (see #156 and #231)?
* How can we keep simple the basic scenario of generating a live-updated metrics report?

**Comment by daavoo** [comment]
> We could start by asserting that report is not open in the default use case.

Unless I am missing something, we already test that:

https://github.com/iterative/dvclive/blob/0aba0c9a28c76e4aa6a21525c552f1791c673dce/tests/test_report.py#L62-L68

**Comment by pared** [comment]
Sorry @daavoo, my bad.

**Comment by mattseddon** [comment]
@daavoo you do assert that but there is nothing stopping you from changing that assert. I.e nothing to say that the VS Code extension is dependent on that behaviour. Maybe it would actually be safer to add an environment variable if this behaviour is going to be kept. WDYT?

**Comment by pared** [comment]
Well, adding env variable is good too, but the fact that we change the test to make it pass should raise a red flag. I am good with both approaches.

**Comment by daavoo** [comment]
Implemented as env var in  #243 and removed the arg from `Live`. I think it makes more sense as this is an environment-dependent feature and only applicable to `html` report

**Comment by mattseddon** [comment]
Will this change ship with the next version of `DVCLive` and then ship with `DVC 2.10.2` as the minimum required version?
