### ISSUE TITLE
`html`: How to track/ignore it in DVC

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvclive#242]
After https://github.com/iterative/dvc.org/pull/3411, the easiest way to track plots in `dvc.yaml` is:

```
    plots:
      - dvclive
```

However, this will track `dvclive/report.html`, which is generally not desired. Some options to handle this better:

* Automatically add `dvclive/report.html` to `.dvcignore` (should we check for the presence of DVC or just add it anyway?).
* Move `report.html` outside of the `dvclive` dir.
* Allow DVC to track it -- is it harmful?

**Comment by dberenbaum** [comment]
One more option would be to always suggest using `cache: false` for plots and capturing all dvclive outputs in git instead of dvc.

**Comment by daavoo** [comment]
> Automatically add dvclive/report.html to .dvcignore (should we check for the presence of DVC or just add it anyway?).

I won't really like to add DVC-specific logic.

> Move report.html outside of the dvclive dir.

Not sure if it's a good idea. General feedback is that DVC/DVCLive already generates too many files at the root of the repo.

> Allow DVC to track it -- is it harmful?

I might be missing something but it would be just wasted storage.

---

What if we encourage through docs to use set outputs for each data subfolder? 

This way the report won't be tracked by DVC and allows for more flexibility. The most common setup, IMO, would be:

```yaml
    plots:
      - dvclive/images
      - dvclive/scalars:
          cache: false
```

**Comment by dberenbaum** [comment]
> What if we encourage through docs to use set outputs for each data subfolder?
> 
> This way the report won't be tracked by DVC and allows for more flexibility. The most common setup, IMO, would be:
> 
> ```yaml
>     plots:
>       - dvclive/images
>       - dvclive/scalars:
>           cache: false
> ```

I think this makes sense for now. It feels a little burdensome to have to add all this to get dvclive outputs tracked properly, but at least it's explicit and flexible.

**Comment by daavoo** [comment]
Would https://github.com/iterative/dvclive/pull/322 close this? Given that plots will be isolated in it's own folder, the following won't track the report:

```
plots:
  - dvclive/plots
```

**Comment by dberenbaum** [comment]
If we are writing `dvc.yaml` from dvclive, is there any downside to adding the report file to dvcignore?
