### ISSUE TITLE
live: Revisit output names

### ISSUE THREAD

**Issue by daavoo** [iterative/dvclive#246]
can we rename it? is it a default name? it's a bit confusing to have `dvclive` dir, `dvclive/scalars` which are actually plots and `dvclive.json` that is actually scalars ... how can we improve this naming? cc @dberenbaum @daavoo wdyt?

_Originally posted by @shcheklein in https://github.com/iterative/vscode-dvc/pull/1618#discussion_r859418877_

**Comment by dberenbaum** [comment]
Related conversation: https://github.com/iterative/dvc.org/pull/3147#discussion_r789079337

**Comment by dberenbaum** [comment]
My take:

* `scalars` seems too technical to me. Can we rename to `trends` to align with VS Code and Studio?
* `dvclive.json` we can probably rename to `metrics.json`. We have also discussed moving it inside `dvclive/metrics.json`, which I think makes sense although I think there are a few technical hurdles to overcome for how to track everything inside `dvclive`.

**Comment by daavoo** [comment]
> Can we rename to trends to align with VS Code and Studio?

It sounds appealing. However, `trends` in VSCode are based on DVC checkpoints, and in Studio are based on commits. 
The `.tsv` files we would be saving in `plots/trends` are actually being currently shown as `Data Series` in VScode and as `Plots` in Studio.

> dvclive.json we can probably rename to metrics.json. We have also discussed moving it inside dvclive/metrics.json, which I think makes sense although I think there are a few technical hurdles to overcome for how to track everything inside dvclive.

Moving `dvclive.json` to `dvclive/metrics.json` + creating a `plots` folder sounds good.

**Comment by dberenbaum** [comment]
Okay, maybe we can hold off on `trends` for now or think of another name.

**Comment by dberenbaum** [comment]
> Okay, maybe we can hold off on `trends` for now or think of another name.

How about `metrics`, so that it looks like:

```
$ tree dvclive
├── metrics.json # renamed from "dvclive.json" and moved inside the dir
├── params.yaml # new
├── plots # align subdir names with VS Code
│   ├── data_series # renamed from "plots"
│   │   └── roc.json
│   ├── images
│   │   └── img.png
│   └── metrics # renamed from "scalars"
│       └── acc.tsv
└── report.html
```
