### ISSUE TITLE
dvclive outputs paths

### ISSUE THREAD

**Issue by sukhovvl** [iterative/dvclive#263]
After updating `dvc` package to the version 2.11.0 I noticed that `dvclive` outputs paths were changed, e.g. `dvclive/scalars/loss.tsv` is now `dvclive/scalars/train/loss.tsv`. I am working with the `dvclive.keras` framework but the change probably affected other frameworks as well.

I would suggest to reflect this breaking change in the documentation [here](https://dvc.org/doc/dvclive/dvclive-with-dvc#outputs).
Being aware about the internal structure of the `scalars` folder is needed since as a minimum these outputs should be tracked by `git` in order to for example create a subsequent `cml` report.
Due to this issue it is currently not possible to use different `dvc` versions to produce such a report.

**Comment by daavoo** [comment]
Hi @sukhovvl , sorry for the inconvenience. This was introduced in `0.9.0` and reflected in the release notes https://github.com/iterative/dvclive/releases/tag/0.9.0

I will update each framework page to reflect this structure better. 

> Being aware about the internal structure of the scalars folder is needed since as a minimum these outputs should be tracked by git in order to for example create a subsequent cml report.

How did this change affect you? Were you tracking individual files under `dvclive/scalars`?

>  Due to this issue it is currently not possible to use different dvc versions to produce such a report.

You can manually pin `dvclive` in your dependencies to use `<0.9.0` as `dvclive` is only pinned in the lower bound in `dvc` requirements (`dvclive>=0.7.3`)
