### ISSUE TITLE
`report`: render inline in ipython

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvclive#309]
Render the report inline within a notebook instead of in a separate HTML/mardown document. Should be prioritized after we have a basic DVCLive-only workflow for parameters/metrics/plots.

**Comment by daavoo** [comment]
This probably belongs in https://github.com/iterative/dvc-render , but I am ok with tracking it here

**Comment by dberenbaum** [comment]
Do we need an issue in both? In dvc-remder to add something like `render_ipython` and here to add support in DVCLive?

**Comment by dberenbaum** [comment]
This feels pretty important now for anyone not using VS Code. Otherwise, it's painful to see the report.
