### ISSUE TITLE
`log_param`: params should be shown in report

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvclive#315]
Not sure if this belongs here or in https://github.com/iterative/dvc-render/, but all the values from `{Live.dir}/params.yaml` should also be shown in the metrics report.

**Comment by daavoo** [comment]
> Not sure if this belongs here or in https://github.com/iterative/dvc-render/

Both

**Comment by daavoo** [comment]
I was mistaken. Forgot that I already added the TableRenderer for metrics. It should be possible to reuse here for displaying parameters:

https://github.com/iterative/dvclive/blob/a4ca09e5b4061015a3f8af6dff83e393efe646c3/src/dvclive/report.py#L72-L74
