### ISSUE TITLE
report: "auto" requires matplotlib in ci

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvclive#333]
By default, dvclive will try to create a markdown report in CI using matplotlib. This means a script that works locally can fail on CI unless matplotlib is specified as a dependency, which can be surprising. Not sure the best way to handle this (change default behavior? just document it?).

**Comment by daavoo** [comment]
> Not sure the best way to handle this (change default behavior? just document it?).

I forgot to add a check in `auto` looking for `matplotlib` installation
