### ISSUE TITLE
studio: Cache credentials

### ISSUE THREAD

**Issue by daavoo** [iterative/dvclive#335]
> do we need to store these tokens stored somewhere in "${XDG_DATA_HOME:-$HOME/.local/share}/dvclive/credentials.toml"? To be able to cache them and not care about setting them all time.
> from @mvshmakov

**Comment by mvshmakov** [comment]
Also, there is a [direnv](https://direnv.net/) for (non-)nix environments which also solves this problem to some extent. Though, say, `gh-cli` and `aws-cli` cache their creds in a way defined in this issue.

**Comment by daavoo** [comment]
Will not be addressed by DVCLive
