### ISSUE TITLE
`log`: make `log_metric` alias?

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvclive#336]
Not sure why anyone would want a longer method, but `log_metric` is more explicit. Is it worth adding for clarification?

**Comment by daavoo** [comment]
> Not sure why anyone would want a longer method

I like it better 😅

**Comment by daavoo** [comment]
Another thing: users might think that `live.log` supports arbitrary types like `wandb.log` but our API is more along the lines of explicit type suffixes like [mlflow.log_metric](https://www.mlflow.org/docs/latest/python_api/mlflow.html#mlflow.log_metric)
