### ISSUE TITLE
version attr missing

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvclive#359]
Need to support a version attribute to check the current version. I'd say it's important with the intro of 1.0.

**Comment by skshetry** [comment]
Users can do that easily with:
```python
from importlib.metadata import version

version('dvclive')
```

**Comment by dberenbaum** [comment]
Judging from https://stackoverflow.com/questions/20180543/how-do-i-check-the-versions-of-python-modules, I guess `dvclive.__version__` may be an outdated/not recommended anymore, although it's still unclear. I still default to that for finding a package version. Do you consider it bad practice? Does it hurt to include it?

**Comment by alex000kim** [comment]
ahaha, I came to this repo to create this exact issue :)

**Comment by skshetry** [comment]
See https://stackoverflow.com/questions/72167802/adding-version-attribute-to-python-module.

I don't see much difference between `version('dvclive')`, and that is in-built into the standard library, and is a canonical truth (even if `dvclive.__version__` may sometimes lie and is just a convention).

Do users want to support multiple versions of `dvclive`? Or, is it for constraining to a certain version? In that case, either restricting via a package manager might be a good option, or an ad-hoc `version('dvclive')`.

Again, I am not opposed to this, it's a simple addition. I was merely suggesting that there are other ways to get the _real_ installed version.

**Comment by alex000kim** [comment]
The only argument I can make is the same as what @dberenbaum said:
> I still default to that for finding a package version.

**Comment by daavoo** [comment]
My vote is to just recommend `importlib.metadata` when someone asks.
