### ISSUE TITLE
random_exp_name: update to use/match dvc

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvclive#396]
`random_exp_name` was broken by https://github.com/iterative/dvc/pull/8659 because it removes `_validate_new_ref`.

**Comment by daavoo** [comment]
Need a DVC release first

**Comment by dberenbaum** [comment]
So that means if we want dvclive bundled with dvc, we need:

1. dvc 2.38.0
2. dvclive 1.2.0
3. dvc 2.39.0

Is that right 😅 ?

**Comment by daavoo** [comment]
"vendoring" the logic from DVC in #399 so there is no version conflict
