### ISSUE TITLE
tests: integrations with DVC

### ISSUE THREAD

**Issue by pared** [iterative/dvclive#4]
Those should probably be made in `dvc` repo, but I create issue here to not clutter the main repo.

- [x] "normal" use case - `dvc --logs` produces plots and metrics
- [x]  checkpoints - we should be able to `plots show/diff` and `metrics diff` for experiments using `checkpoints`

**Comment by aguschin** [comment]
@pared, in case this will be useful: while trying out dvclive I found out that `dvc metrics diff` doesn't show anything I logged with dvclive, until I add that directly to dvc.yaml:
```
    metrics:
      - metrics.json:
          cache: false
```
I was expecting to see a final dvclive json with metrics in `dvc metrics diff` along with other metrics stored by dvc without adding this. If we won't be adding this functionality, it may be worth mentioning in the dvclive docs. 

Could you please clarify how this is supposed to work eventually?

**Comment by daavoo** [comment]
@pared can this be closed, given https://github.com/iterative/dvc/blob/master/tests/func/test_live.py ?

**Comment by pared** [comment]
@daavoo you are right!

**Comment by pared** [comment]
For sake of preserving the history i provide link to particular version:
https://github.com/iterative/dvc/blob/2.5.4/tests/func/test_live.py
