### ISSUE TITLE
dvc: `save_dvc_exp` doesn't work if repo has `.dvc` files.

### ISSUE THREAD

**Issue by daavoo** [iterative/dvclive#408]
If a repo contains `.dvc` files (via `dvc add` or `dvc import`) `save_dvc_exp` will be incorrectly skipped.

After fixing the incorrect skip, there is another issue that `exp save` tries to `dvc commit` those files, failing and requiring `--force` flag.

Even if that failure can be avoided with `--force`, it is unclear if DVCLive (via `exp save`) should be running `dvc commit` at all.

--- 

Thanks @SoyGema for uncovering this bug

**Comment by dberenbaum** [comment]
I think 

> Even if that failure can be avoided with `--force`, it is unclear if DVCLive (via `exp save`) should be running `dvc commit` at all.

Let's use `--force` and commit those files. It's similar to changes in dependencies during `dvc exp run`. We commit those before running the experiment.

**Comment by daavoo** [comment]
> Let's use --force and commit those files. It's similar to changes in dependencies during dvc exp run. We commit those before running the experiment.

I worry this might cause some unexpected behavior if someone tries the DVCLive-only experiments in a repo where they also manually manage data with DVC. 
Not sure how common of a scenario that would be

**Comment by dberenbaum** [comment]
TBH I think I missed the behavior of `dvc exp save --force` and I think this should actually be the default behavior of `dvc exp save` @dtrifiro. There was a [long similar convo](https://github.com/iterative/dvc/issues/5593) about `dvc exp run`, and ultimately both `dvc repro` and `dvc exp run` forcefully commit any changes to dependencies. I think this will also be useful if we want dvclive to log artifacts on each run.

**Comment by dberenbaum** [comment]
> both `dvc repro` and `dvc exp run` forcefully commit any changes to dependencies

Actually, I just double checked. `dvc repro` commits changes to dependencies, and `dvc exp run` commits all changes even if they are not dependencies. Regardless, if it hasn't been an issue yet for `dvc exp run`, it's probably safe to commit for `dvc exp save`. It may be more surprising if `dvc exp save` doesn't commit and then users transition to `dvc exp run`, which does.
