### ISSUE TITLE
`log_image` does not work with file-based Images

### ISSUE THREAD

**Issue by rkern** [iterative/dvclive#412]
Many APIs that generate images that I want to log (e.g. matplotlib's `Figure.savefig()`) will write out to a formatted file (or filelike object) that then needs to be read by `PIL` to create the `Image` object. Those objects are typically instances of format-specific subclasses of `PIL.Image.Image` and not direct instances of `PIL.Image.Image` itself. The [existing check](
https://github.com/iterative/dvclive/blob/main/src/dvclive/plots/image.py#L17-L22) will not detect those objects because it only looks at the exact type and not its superclasses.

Instead, traversing the MRO and checking the `(cls.__module__, cls.__name__)` pair against a known list would be more robust. This is a reasonably common pattern for doing lazy `isinstance()` checks for types when you don't want to actually do the import.

```python
    def could_log(val: object) -> bool:
        acceptable = {
            ("numpy", "ndarray"),
            ("PIL.Image", "Image"),
        }
        for cls in type(val).mro():
            if (cls.__module__, cls.__name__) in acceptable:
                return True
        return False
```

**Comment by daavoo** [comment]
> Instead, traversing the MRO and checking the (cls.__module__, cls.__name__) pair against a known list would be more robust. 

Thanks @rkern ! That's definitely better
