### ISSUE TITLE
Tensorflow 2.10 Integration with DVCLive 1.3.1 In VsCode Extension

### ISSUE THREAD

**Issue by SoyGema** [iterative/dvclive#422]
Hello there! 
Congratulations in all the advancements related to DVCLive and bringing out a easier and straightfoward manner to conduct machine learning experiments ! 🥇 

Under the context of [Neural Machine Translation Tutorial](https://github.com/SoyGema/Neural-Machine-Translation/blob/main/src/models/train_transformer.py#L211) and executing `dvc exp run train_transformer` , Im facing some unexpected behavior that I would like to share with you .

1. Live metrics are not being displayed in **plots** or in **table**. I´m guessing something is wrong with my dvc.yaml file ? 
  I´ve changed the [paths](https://github.com/SoyGema/Neural-Machine-Translation/blob/main/dvc.yaml#L81) for metrics and follow [documentation ](https://dvc.org/doc/dvclive/api-reference/ml-frameworks/tensorflow) with code above . I know the model is training because I can print the metrics on CLI. I might be missing something , so apologies in advance ... 

2. Super minor . This warning appears more than 20 times in between the printing of the metrics in CLI

```WARNING:dvclive:`post_to_studio` `data` event failed. Data will be resent on next call.```

Not making any harm per se , just a little bit annoying in between printing metrics in epochs.

Thanks in advance for the time dedicated to this, and congratulations !!

**Comment by SoyGema** [comment]
Findings : 

2a. The message seems to be part of Live class and [make_report](https://github.com/iterative/dvclive/blob/de57fbd796136a02569abed8266d2d6505406143/src/dvclive/live.py#L340) method . Apparently the message is shown when there is **no response** for logging to studio . 
2b. The method [next_step](https://github.com/iterative/dvclive/blob/de57fbd796136a02569abed8266d2d6505406143/src/dvclive/live.py#L243) calls make_report() wether we are integrated with studio or not and makes it if report_mode is not None .

This seems to be also confusing for [some user](https://discord.com/channels/485586884165107732/563406153334128681/1059919252175454339) thanks @daavoo for covering this Q in discord !

**Comment by daavoo** [comment]
Thanks @SoyGema 

> Live metrics are not being displayed in plots or in table. I´m guessing something is wrong with my dvc.yaml file ?

The paths need to be defined as in this P.R: https://github.com/SoyGema/Neural-Machine-Translation/pull/2/files

> Super minor . This warning appears more than 20 times in between the printing of the metrics in CLI

This should be fixed in https://github.com/iterative/dvclive/pull/423 and available on next release
