### ISSUE TITLE
sklearn plots formatting: fix plot templates

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvclive#424]
There are a couple formatting issues that make the sklearn plots hard to read.

First, since https://github.com/iterative/dvc-render/pull/107, the points obscure the lines.

![visualization(15)](https://user-images.githubusercontent.com/2308172/211443111-656dce17-1c87-4b86-91a2-54e278435bd8.png)

Second, without the points, the lines are too noisy and need smoothing.

![visualization(17)](https://user-images.githubusercontent.com/2308172/211443171-0b036d5c-8e1b-44a4-9258-cbba43729779.png)

Two possible solutions to this are:

1. Use the `smooth` template for these plots (which may need to be updated with some of the recent `linear` changes).
2. Include options for hiding points and smoothing in the default `linear` template.

<img width="522" alt="Screenshot 2023-01-09 at 8 49 29 PM" src="https://user-images.githubusercontent.com/2308172/211443495-5ebfda91-b829-4aab-925b-0f0845a90b61.png">

**Comment by daavoo** [comment]
@dberenbaum Which repo is generating those plots? 

Don't mean to dismiss the issue but those curves look extremely noisy.

**Comment by dberenbaum** [comment]
It's from example-get-started. The plots for it now look like the top image, so I think we need to do something to get them looking reasonable again.

**Comment by dberenbaum** [comment]
For long-running jobs, the metrics plots might also need smoothing (similar to tensorboard), so I'd lean towards including smoothing by default (see https://github.com/iterative/dvc/issues/8396).

**Comment by dberenbaum** [comment]
@daavoo What do you think about adding the radio and slider by default? Is it too much?

**Comment by dberenbaum** [comment]
@daavoo @shcheklein Taking a step back, it seems we have a decent default for scalar trends now, and we should probably include the smoothing slider for any plots like this. There doesn't seem to be much point hiding this in a separate smooth template.

I think it's important to have a simpler linear plot with no points and no smoothing for the sklearn plots (I suggested smoothing above, but thinking about it some more I wouldn't want it for these plots). ROC and precision-recall plots are some of the most common eval plots, they depend on being able to see the intricacies of the curves, and they usually have a number of points on the order of the size of the eval data (too many to show individually). Seeing the jagged line breaks like the ones above can indicate where there are irregularities or peaks and valleys of performance. Similar to the request in https://github.com/iterative/dvc-render/issues/103, the thresholds matter because you may consider everything beyond a certain threshold as a positive prediction and everything else as a negative prediction, and looking at the breaks in these plots may help determine where to set that threshold.

I see two options for addressing the sklearn plots:
1. Reusing the template used for scalars, which I think is a worthwhile goal because it greatly reduces friction to modifying plots, but maybe it ends up not working well enough for either scenario.
2. Having a simpler template for the sklearn plots that excludes points and smoothing. We could reintroduce the simple template or think of another way to better describe the differences.

What do you think?
