### ISSUE TITLE
Support for `pathlib` paths

### ISSUE THREAD

**Issue by alex000kim** [iterative/dvclive#428]
Doing this `DVCLiveCallback(dir=Path("results")/"train", ...)` errors out with:
```
TypeError: Exception occured in `DVCLiveCallback` when calling event `after_fit`:
	argument of type 'PosixPath' is not iterable
```

(`DVCLiveCallback(dir="results/train", ...)` works)

**Comment by swarajpande4** [comment]
Hi @alex000kim and @daavoo, I tried to replicate this error on my local. However, I did not encounter any exception when I used Path instance for dir. Can more insight be provided for replication of this error ? 
Thanks.
