### ISSUE TITLE
Overwrite manually logged images

### ISSUE THREAD

**Issue by svsn2117** [iterative/dvclive#431]
Hey guys, thanks for your great work!

I'm logging a plot using `live.log_image(filename, fig_pil)` as part of my notebook. Now, we usually need a couple of tries to get the plot that we want. It would be great if dvclive could overwrite an already logged image file instead of throwing an `DataAlreadyLoggedError`. Otherwise, managing this becomes a huge headache when you are working with multiple plots or images.

For example, as additional argument: 
```Python
log_image(name, val, overwrite=True)
```

Thanks for considering!

**Comment by dberenbaum** [comment]
I think we could even just drop this check and leave it to the users to make sure they don't overwrite. WDYT @daavoo?

**Comment by daavoo** [comment]
> I think we could even just drop this check and leave it to the users to make sure they don't overwrite. WDYT @daavoo?

Yep

**Comment by dberenbaum** [comment]
@svsn2117 Would you have an interest in contributing that change?

**Comment by svsn2117** [comment]
I might try, but first I have to get the local env setup (see https://github.com/iterative/dvclive/issues/433). From what I have looked into so far, it doesn't look like a lot of work for someone more familiar with the project than me. I would recommend changing not only `log_images` but all `log_` functions though.

**Comment by dberenbaum** [comment]
Sounds good @svsn2117! Yes, I don't think it's a lot of work, but I can't promise how soon we can prioritize it, and it's always great to have contributions from the community. If not, no worries, we will get to it at some point.

**Comment by dberenbaum** [comment]
Fixed in #445
