### ISSUE TITLE
Missing data in dvclive to be displayed by "dvc exp show"

### ISSUE THREAD

**Issue by nv-pipo** [iterative/dvclive#435]
Following the documentation in:
- https://dvc.org/doc/user-guide/experiment-management/checkpoints

The output of "dvc exp show" and "dvc metrics diff" that I can produce differs from the official documentation: The columns of metrics and steps are missing.

Output with latest dvc:
<img width="561" alt="output produced" src="https://user-images.githubusercontent.com/7769945/215275602-0abc89f6-f6af-49aa-8b55-d0a39144ab50.png">

Expected:
<img width="690" alt="expected" src="https://user-images.githubusercontent.com/7769945/215275609-14fcebdd-b328-4ac5-9a88-9f70c3fa1cc1.png">

Am I missing any flag in "dvc exp show"/"dvc metrics diff"? Should I report this to DVC repo instead? it seems to me that it is more a dvclive issue, hence the report here.

**Comment by dberenbaum** [comment]
Hi @nv-pipo! Could you give some more details. Do you have a `dvc.yaml` pipeline? If so, what does it look like?

**Comment by nv-pipo** [comment]
Hi @dberenbaum,
Thanks for following up!

When saving checkpoints via ```dvc exp run``` the experiment parameters are not tracked. Note that using the "Python API" (```python train.py``` and setting ```save_dvc_exp=True```) the parameters are correctly tracked.

To replicate:
~~~python
# python.py
from random import random

from dvclive import Live

NUM_EPOCHS = 2

with Live(save_dvc_exp=True) as live:
    live.log_param("epochs", NUM_EPOCHS)

    for epoch in range(NUM_EPOCHS):

        live.log_metric("metric_name1", random())
        live.next_step()
~~~
~~~yaml
# dvc.yaml
stages:
  train:
    cmd: python train.py
# live:
#   dvclive:
#     summary: true
#     html: true
~~~
Then run:
~~~shell
git init
git add .
git commit -am 'Initial'
dvc init
dvc exp run
dvc exp show
~~~
The experiment (checkpoint) is tracked but the parameters and metrics are not saved/show by ```dvc exp show```. Output of last 2 commands:
<img width="872" alt="Screenshot 2023-01-31 at 20 41 49" src="https://user-images.githubusercontent.com/7769945/215865742-a248b796-2c73-48a5-a9a3-c828c3433257.png">


However this works without issues when using the "Python API":
~~~shell
rm -f dvc.yaml
python train.py
dvc exp show
~~~
<img width="1447" alt="Screenshot 2023-01-31 at 20 41 59" src="https://user-images.githubusercontent.com/7769945/215865718-4715c6c7-70ed-4b22-a3a1-d6687b0cb7b7.png">

Thanks!
Nicolas

**Comment by daavoo** [comment]
Fixed in https://github.com/iterative/dvclive/pull/440

**Comment by dberenbaum** [comment]
@nv-pipo Could you do `pip install --upgrade dvclive` and confirm whether it's working as expected for you now?

I'd also recommend that you add the `dvclive` directory to your `train` stage:

```
# dvc.yaml
stages:
  train:
    cmd: python train.py
    outs:
      - dvclive:
          cache: False    
```

This will monitor the `dvclive` directory as another output of your stage. `cache: false` is optional but useful for small metrics files. It will prevent DVC from caching the output so that you can track the results in Git.

**Comment by nv-pipo** [comment]
@dberenbaum,
Thanks for the prompt action!
I confirm that the latest version works as expected: running an experiment with ```dvc exp run```, tracks parameters/metrics (displayed by ```dvc exp show```).

PS: It also works when using queues and multiple threads for processing. Eg running multiple ```dvc exp run --queue -S ...``` followed by a ```dvc exp run --run-all``` and finally a ```dvc exp show```
