### ISSUE TITLE
docs: fix README and create documentation entry for dvclive

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvclive#45]
> Part of iterative/dvc.org/issues/2026

UPDATE: Jump to https://github.com/iterative/dvclive/issues/45#issuecomment-858538315

Any chance you could make a quick draft for the needed API refs in https://dvc.org/doc/api-reference and maybe expand the README in this repo if needed to cover all the features @pared ? No need for details at first, just trying to cover everything even if it's just a brief mention of what you can do/how. Thanks

**Comment by pared** [comment]
Related to https://github.com/iterative/dvc.org/pull/2227

**Comment by daavoo** [comment]
What is the state of this issue after https://github.com/iterative/dvclive/pull/71 ? Is this blocked by https://github.com/iterative/dvc.org/issues/2443 ?

**Comment by pared** [comment]
I think that #71 covers pretty much all relevant changes required for this to be closed, but we could leave this open and polish it according to iterative/dvc.org#2443. So far README is lacking:
- installation methods
- links to related technologies
- link to Contributing (though call for collaboration is probably enough for now)
- licen[c/s]e & citation
