### ISSUE TITLE
Scikit-learn integration

### ISSUE THREAD

**Issue by JenniferHem** [iterative/dvclive#452]
Hi dvclive Team,

we just started exploring the vast world of MLops and DVC. I really like the DVC experiments part. Our main framework we are using is scikit-learn and I did not find an integration into dvclive. I saw that there was a discussion in #5 but that seems like there was not really any conclusion. 
So I was just wondering, are there plans for scikit-learn or should we use our own tracking functions?

Thanks,
Jennifer

**Comment by daavoo** [comment]
Hi @JenniferHem , could you give some more details on what you would expect to log from `scikit-learn`? Were you thinking in some sort of auto-logging?

DVCLive provides integrations in the form of callbacks for frameworks based on training with iterations (usually deep learning).

For other cases, DVCLive provide a Python API for logging different type of data https://dvc.org/doc/dvclive/api-reference#log-data , including plots that are created using scikit learn (https://dvc.org/doc/dvclive/api-reference/live/log_sklearn_plot) . 

This API can be used alongside scikit-learn, we use this method for example in:

https://github.com/iterative/example-get-started/blob/main/src/evaluate.py

**Comment by JenniferHem** [comment]
Hi @daavoo. Yes I was thinking about auto logging (basically roughly what the evaluate example does. In addition, maybe logging of the model parameters, however I have not seen if this is also the purpose of dvclive (yet). 
Since I am fairly new to all the MLops things I can't really give you a full picture yet but your links definitely help me to wrap my head around dvclive a bit better. 
So for now that already helps me a lot! In case I would have specific suggestions (once I have experimented with the new info) I would be happy to come back to you.

**Comment by daavoo** [comment]
> So for now that already helps me a lot! In case I would have specific suggestions (once I have experimented with the new info) I would be happy to come back to you.

Don't hesitate to comment here. I am closing the issue for now
