### ISSUE TITLE
report: auto mode and when to show the report

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvclive#459]
#432 introduces `report="notebook"`. Turning this on automatically may be too aggressive for some, but others may never discover it if we turn it off by default. I also expect that users rely less on the report now that we have other ways to show live updates, like in the VS Code extension or even Studio. 

Do we still need `auto` mode at all? Should it be the default? What should its behavior be? It gives an obvious intro to the reports DVCLive can generate, and it can always be turned off, but I don't think it's behavior is obvious, and adding more report types to it only makes it more complicated.

**Comment by daavoo** [comment]
I was thinking that for 3.0 I would prefer the default to be `None`, drop `html` creation by default.

**Comment by dberenbaum** [comment]
Yup, I'm fine with that.
