### ISSUE TITLE
frameworks: Use `log_artifact`

### ISSUE THREAD

**Issue by daavoo** [iterative/dvclive#465]
Once #378 is done, it would be nice to automatically use it under the hood in the frameworks where we currently support saving the model, i.e.:

https://github.com/iterative/dvclive/blob/41d12d7936c7a781a30da27e7fd12faa00b34a1e/src/dvclive/keras.py#L49-L53

To:

```python
        if self.model_file:
            if self.save_weights_only:
                self.model.save_weights(self.model_file)
            else:
                self.model.save(self.model_file)
            self.live.log_artifact(self.model_file)
```

**Comment by dberenbaum** [comment]
Even better would be if DVCLive can inspect if other callbacks are being used to save the model and use `log_artifact` to track those paths.

**Comment by dberenbaum** [comment]
@daavoo Can you take this as a follow-up to #464?

**Comment by daavoo** [comment]
> @daavoo Can you take this as a follow-up to https://github.com/iterative/dvclive/pull/464?

Yep! was already planning on it 🚀 
I was also already counting on adding the `type=model` meta field as it doesn't really break anything to include it

**Comment by dberenbaum** [comment]
> I was also counting on including the `type=model` meta field as it doesn't really break anything to include it

Thanks! First need to settle the discussion on how to handle `type=model` from https://iterativeai.slack.com/archives/CB41NAL8H/p1678197700155189.

**Comment by daavoo** [comment]
> r how the model_file can be used without throwing warnings while still being part of the outs:

Hi @SH2282000 , the `dvc.yaml` you shared is correct and the warnings should not appear in the latest version of DVCLive.
