### ISSUE TITLE
studio: live metrics for `dvc repro`

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvclive#474]
Opening a new issue so we can consolidate discussion in one place. 

Live metrics theoretically work regardless of how you run your experiment. Someone could run `dvc repro` with DVCLive and `STUDIO_TOKEN` and expect to get live metrics in Studio. In fact, this is maybe the most common way I would expect it to be used 😅 because:

1. Studio live metrics seem most useful in CI.
2. We know that most CI/CML jobs use `dvc repro`.

We could encourage people to use `dvc exp run` instead, but I have some concerns with that approach:

1. Makes it harder for users to onboard since they have to migrate to a different workflow in their CI, which may not seem worth it since it could introduce unexpected problems.
2. `dvc exp run` has known limitations (for example, requiring non-default fetch depth) when running in CI. It doesn't seem to have any real advantages when running in CI.

What are the downsides to allowing Studio live metrics inside `dvc repro`?

**Comment by daavoo** [comment]
> What are the downsides to allowing Studio live metrics inside dvc repro?

No experiment ref.

**Comment by dberenbaum** [comment]
> No experiment ref.

Do I want an exp ref in CML? Is it just going to add yet another row in Studio with the same info? Or should we work towards having the end result of a CML workflow be an exp ref instead of a regular commit? What would be the pros/cons?

**Comment by daavoo** [comment]
> Is it just going to add yet another row in Studio with the same info?

You are already adding one row for the live experiment, even though it is not an exp ref.

> Or should we work towards having the end result of a CML workflow be an exp ref instead of a regular commit? 

IMO, Yes. 

The workflow should serve as a replacement for the current `cml pr/cml report` towards making it more Studio centric. 
CML should just be used for provisioning the runner.

People that don't want to use Studio can still use the old CML workflow, but they obviously don't need live experiments in Studio.

> What would be the pros/cons?

From the top of my mind:

### Cons

- People would need to update the workflow to use the live experiments (although they already need to update it for STUDIO_TOKEN).
-`cml report` supports arbitrary Markdown report.
- Studio doesn't have an individual view per experiment, would need to implement a way to share a useful link for going from GitHub to the experiment in Studio.

### Pros

- Simpler workflow file for onboarding.
- Studio-centric 
- Cleaner UI in Studio (row mess when using `cml pr`).
- Cleaner git history (branch and p.rs by `cml pr` even if you end up discarding the experiment).
- Unification of the different concepts of `experiments`.

**Comment by dberenbaum** [comment]
That makes sense @daavoo! I agree with the overall direction.

The one thing that I have noticed that doesn’t work on custom refs in GitHub is triggering workflows, so I think at least the initial branch + commit might be needed ☹️ . I worry a little that it's hard to come up with a clean workflow combining that initial branch + commit and an exp ref at the end, especially if you also include live metrics.

**Comment by daavoo** [comment]
> custom refs in GitHub is triggering workflows, so I think at least the initial branch + commit might be needed ☹️

I think we can work around that. 

We are already making an (IMO) broad assumption in Studio `Run Experiment`, expecting people's workflows to be triggered on any branch commit for any change.

This assumption doesn't really hold for a real example (triggering on every commit), see the[ get-started setup](https://github.com/iterative/example-get-started-experiments/blob/982941e239db6a7628ab9d327e7424fdef09429e/.github/workflows/run-studio-experiment.yml#L4-L16) as an example of the modifications that users most likely need to make in real projects.

Afaik, GitHub GitLab and BitBucket support triggering workflows based on external events, for example:

https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#repository_dispatch

Instead of creating a commit, Studio could trigger the workflow using that mechanism.

It doesn't sound like an unreasonable assumption/request for people to configure the workflows for that trigger (again, we are already assuming/requesting people to properly handle commit events)

**Comment by daavoo** [comment]
The downside is that we would be losing some of the features in Studio like modifying data/params from the Run Experiment. 

A more elaborated workflow setup would allow working around that, for example (webhook can include inputs in the payload):

```yaml
  workflow_dispatch:
    inputs:
      params:
        type: string
...
  - name: train
      run: dvc exp run -S ${{ github.event.inputs.params }}
```

Given that we already provide templates for users, would be a matter of setting one for covering all this

**Comment by dacbd** [comment]
> We are already making an (IMO) broad assumption in Studio Run Experiment, expecting people's workflows to be triggered on any branch commit for any change.

I agree, on the front of the studio-generated workflow, I never envisioned it as the end all be all. Triggering on every commit is a bad idea and was meant to be a placeholder. Perhaps tweaking this or better communicating it could be helpful.


> Afaik, GitHub GitLab and BitBucket support triggering workflows based on external events, for example:
>
> https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#repository_dispatch
> 
> Instead of creating a commit, Studio could trigger the workflow using that mechanism.

I think this is worth investigating as a better approach to the CI-Based experiment running.

----
Personally in my mind I picture `dvc repro` being distinct from `dvc exp run` where you are more literally "reproducing" your model with the same params to either sync your local state to some existing experiment or when some underlying data has changed in some form of an automated periodic retraining pipeline. I think there are several cases where users have some form of control step in their dvc pipeline that queries a db or checks the date to determine when to do a "fresh" run. cc @alex000kim 


In my mental model a `dvc repro` is less of an experiment in that you more dealing with data (and I feel almost always followed by a commit) whereas `dvc exp run` is more about learning what params work best/hyperparameter tunning/ running many experiments with say hydra and then picking the best combo of params.

**Comment by dberenbaum** [comment]
> The downside is that we would be losing some of the features in Studio like modifying data/params from the Run Experiment.

Agreed, I was assuming this was the hard part to overcome, not the trigger.

> A more elaborated workflow setup would allow working around that

I looked into this but it feels pretty hacky without better support from Git providers for more dynamic workflows with variable numbers of input parameters.

---

I don't mean to discourage this direction. I think we should try to go this way, but I have tried to play around with all this starting with when we were looking into how to run distributed hyperparameter tuning. So far, I have struggled with some of these hurdles and found that dedicated branches seemed less problematic in a CML workflow.

**Comment by daavoo** [comment]
> with variable numbers of input parameters.

The workflow could have a single arg and make it `dvc exp run ${{ github.event.inputs.exp-run-args }}`. It would be up to Studio to build the string with all required args (i.e. multiple `-S`).

The data updates would still be tricky (maybe solved if https://github.com/iterative/dvc/issues/6491 ?) 

> In my mental model a dvc repro is less of an experiment in that you more dealing with data (and I feel almost always followed by a commit) whereas dvc exp run is more about learning what params work best/hyperparameter tunning/ running many experiments with say hydra and then picking the best combo of params.

I think this is just a matter of how we message it and naming. 

If we reduce inconsistencies, the difference between `dvc repro` and `dvc exp run` behavior would just be a minor overhead and the creation of a custom git ref for the experiment. 
In use cases such as the ones you describe for `dvc repro`, the exp ref could be discarded (maybe we could introduce `dvc exp run --no-ref`?) and everything in the workspace should look equivalent to a `dvc repro` execution.

**Comment by dberenbaum** [comment]
> Personally in my mind I picture `dvc repro` being distinct from `dvc exp run`

💯 I talked with @daavoo about this earlier, and I think you nailed it @dacbd. There are really two different cloud workflows:

1. CI/CML workflows that are about running the latest updates through the training process.
2. Experimentation on cloud machines.

My concern was that `dvc repro` seems like a popular and reasonable default for 1. @daavoo suggested that `dvc exp run` still can give some advantages like saving the user from having to add git and cml steps to their workflow to commit everything generated during `dvc repor`. If we can make sure this works cleanly for the CI scenario, it makes sense to try to encourage `dvc exp run` here.

For 2, I think it's clear that `dvc exp run` should be used. What's also becoming clear is that GitHub actions are insufficient for this workflow, and hopefully the cloud experiments that @dacbd is developing can provide the flexibility we are missing with GHA. @dacbd Is there somewhere that you have high-level discussions or plans about cloud experiments?

**Comment by dacbd** [comment]
Agreed, if we can get things simplified on the running experiments front with `dvc exp run` that makes everyone's lives better in more ways than one.

Unfortunately, I don't think a single good link exists for a high-level discussions/plans about cloud experiments after the turnover and it has also gone through a few scope refinements. When you boil it down the goal is to create the simplest path to running `dvc exp run -S...` in the "cloud" without needing to leave studio.

**Comment by shcheklein** [comment]
Folks, how about the case when I just want to run my script / notebook w/o DVC at all? And see live metrics. The first part of the VS Code onboarding is just about that - run yourself -> get metics. Should we support live metrics in that case?

**Comment by dacbd** [comment]
That use case was our original "Cloud experiments" target but is now to be saved for a follow-up.

**Comment by dberenbaum** [comment]
> Folks, how about the case when I just want to run my script / notebook w/o DVC at all? And see live metrics. The first part of the VS Code onboarding is just about that - run yourself -> get metics. Should we support live metrics in that case?

We already set up a DVC project and suggest calling DVCLive with `save_dvc_exp=True`, so I think we should have no problem with generating an exp ref and supporting live metrics here. Whether there is some scenario where it will be important to support it without a DVC project or exp ref is less clear to me.

**Comment by daavoo** [comment]
My main point here is: if we release a DVC version where `dvc repro` is actually an alias for `dvc exp run`, would people notice it? 

If not, then what is the point of the discussion? 
If yes, in which cases users would notice it?

**Comment by dberenbaum** [comment]
Relevant discussion for what the CI workflow should look like with `dvc exp run`: https://discord.com/channels/485586884165107732/1082598407392206851

**Comment by dacbd** [comment]
Sorry for the late response. I think that most* CI users of `dvc repro` would notice. I believe it was mentioned but due to GitHub Actions `actions/checkout` by default doing a shallow clone if a plain `dvc exp run` requires the git history to make exp refs then it would cause issues.


If a plain `dvc exp run` runs totally fine on a shallow repo then I don't know of any reason why it couldn't be a an alias.

**Comment by dberenbaum** [comment]
Thanks @dacbd! FYI, the shallow clone issue was fixed, so hopefully it's easier now to use `dvc exp run` in CI.
