### ISSUE TITLE
studio: send non-dvclive info

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvclive#476]
DVCLive should be able to send all info collected by DVC, not only that logged by DVCLive. Context:

> Update on DVCLive + Studio:
>
> For context, this is a relatively fresh repo using Lightning and it contains no commits with a metric. I can see live experiments, but they're missing both metrics (the columns don't exist yet) and parameters.
>
> Looking into the Lightning callback code, I notice that you use Live.log_params on the LightningModule hyperparameters, but I don't think that's right, since they're usually a (differently labelled) subset of DVC parameters. I'll probably monkey patch the DVCLogger method, but it'd be nice to have that an option to use /params.yaml as the hyperparameters transmitted to Studio.

**Comment by daavoo** [comment]
> DVCLive should be able to send all info collected by DVC, not only that logged by DVCLive. Context:

I would prefer that DVC info is sent by DVC.

When using `dvc exp run`, DVC params are sent by DVC and DVCLive params are sent by DVCLive.
There is a bug in the UI that doesn't display the DVC ones https://github.com/iterative/studio/issues/5034
