### ISSUE TITLE
3.0 updates

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvclive#484]
```[tasklist]
- [ ] https://github.com/iterative/dvclive/issues/499
- [x] Set `save_dvc_exp=True` by default
- [x] Set `report=none` by default
- [ ] https://github.com/iterative/dvclive/issues/704
```

Post-release:

https://github.com/iterative/dvclive/issues/221

**Comment by daavoo** [comment]
Edited to add https://github.com/iterative/dvclive/issues/499

**Comment by daavoo** [comment]
@dberenbaum we could do 3.0 to match DVC 3.0

**Comment by dberenbaum** [comment]
Do you think we can get all the callbacks moved to their frameworks? We probably can't count on it, but I'm open to trying.

**Comment by shcheklein** [comment]
> Do you think we can get all the callbacks moved to their frameworks? We probably can't count on it, but I'm open to trying.

My 2cs sound like a good to have vs something that improves the experience. I would personally try to prioritize more features, plot improvements, think what we can do to further simplify the onboarding (e.g. making it work w/o .dvc, next steps in moving to pipelines, etc). What else we can do to simplify things?

**Comment by dberenbaum** [comment]
@shcheklein I was just responding to @daavoo, so I'm not pushing for this, but the primary utility IMO is to get more exposure and position dvclive as an alternative on par with other loggers. Until we put it into those frameworks, it looks like something I'd be wary of using because it doesn't seem like it's well supported or taken seriously.

**Comment by shcheklein** [comment]
> @shcheklein I was just responding to @daavoo,

I totally get it, Dave! Read my comment is just like literally "my 2cs", not trying to move it one direction or another.

**Comment by dberenbaum** [comment]
Added item: Set `report=none` by default

I don't think the default html report is that useful these days.

**Comment by daavoo** [comment]
I think we should leave out the following:

- https://github.com/iterative/dvclive/issues/491
- https://github.com/iterative/dvc/issues/9709

Both are dragged from early design decisions and feel like it would be the "correct" way of doing things. However, I worry that we will add friction and/or potential issues for existing users regardless of any effort to make it smooth.

**Comment by dberenbaum** [comment]
I also think #221 should be an action item post-release, so the plan would be:

1. 3.0 release
2. Add callbacks to frameworks
3. Deprecate internal callbacks in 4.0
