### ISSUE TITLE
dvclive: Can't save experiment without a DVC Repo while inside a DVC repo.

### ISSUE THREAD

**Issue by Jarartur** [iterative/dvclive#486]
# Bug Report

## Description

When trying to use:

`with Live(dir="data/dvclive", save_dvc_exp=True) as live:`

It throws a warning and doesn't create a dvc experiment. DVC repo is initialized as stated by running `dvc init`:

`ERROR: failed to initiate DVC - '.dvc' exists. Use `-f` to force.`

Also when trying to specify

```
live:
    dvclive:
        summary: True
```

in dvc.yaml it throws:

```
'.\dvc.yaml' validation failed.

extra keys not allowed, in stages -> train -> live, line 14, column 7
  13 │   live:
  14 │     dvclive:
```

### Reproduce

Launch a python script with

`with Live(dir="data/dvclive", save_dvc_exp=True) as live:`

in a dvc repo.

### Environment information

*(without the live: part of dvc.yaml)*

```
DVC version: 2.41.1 (exe)
---------------------------------
Platform: Python 3.10.9 on Windows-10-10.0.22621-SP0
Subprojects:

Supports:
        azure (adlfs = 2022.11.2, knack = 0.10.1, azure-identity = 1.10.0),
        gdrive (pydrive2 = 1.10.1),
        gs (gcsfs = 2022.11.0),
        hdfs (fsspec = 2022.11.0, pyarrow = 10.0.1),
        http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
        oss (ossfs = 2021.8.0),
        s3 (s3fs = 2022.11.0, boto3 = 1.21.21),
        ssh (sshfs = 2022.6.0),
        webdav (webdav4 = 0.9.7),
        webdavs (webdav4 = 0.9.7),
        webhdfs (fsspec = 2022.11.0)
Cache types: hardlink, symlink
Cache directory: NTFS on C:\
Caches: local
Remotes: ssh
Workspace directory: NTFS on C:\
Repo: dvc, git
```

**Additional Information (if any):**:
DVC yaml schema detects the aforementioned dvc.yaml problem as a correct yaml. Also examples on the dvc's yaml schema repo show the use of it.

**Comment by daavoo** [comment]
Hi @Jarartur , thanks for reporting. 
You have found some rough edges of the current experience that we are trying to smooth.

> It throws a warning and doesn't create a dvc experiment. DVC repo is initialized as stated by running dvc init:

So this first error is because DVCLive requires DVC to be installed as a Python library. 
The logging message is misleading but I can see from the `dvc doctor` output that you have `DVC version: 2.41.1 (exe)`. The current workaround is to `pip install dvc`.

There is a discussion about this on https://github.com/iterative/dvclive/issues/397.
Starting from the next version, DVCLive will include the DVC Python Library so this error should be gone.

> Also when trying to specify

`live` section was deprecated and there should not be mentions in the docs. Could you share where did you find it?

By default, DVCLive will write a hidden `dvc.yaml` only declaring metrics and plots in `dvclive/dvc.yaml`, so even if you don't specify `metrics` and `plots` in your root `dvc.yaml`, all the DVC commands and UI should show them.

Alternatively, you can explicitly specify `metrics` and `plots` in your root `dvc.yam` as:

```yaml
stages:
  train:
    cmd: python train.py
    metrics:
      - data/dvclive/metrics.json:
          cache: false
    plots:
      - data/dvclive/plots:
            cache: false
```

And set `dvcyaml=False` in your Python script:

```python
with Live("data/dvclive", save_dvc_exp=True, dvcyaml=False) as live:
```

**Comment by Jarartur** [comment]
Oh, thank you for the detailed answer.
The aforementioned dvclive is in yaml schema for vs code: https://github.com/iterative/dvcyaml-schema/blob/master/examples/valid/outs.dvc.yaml

I tried again on my linux server but unfortunately I get this error:

```
----> 1 with Live(dir="temp/dvctest4", dvcyaml=True, save_dvc_exp=True) as live:
      2     live.log_param("epochs", 10)

File ~/micromamba/envs/haa-segmentation/lib/python3.10/site-packages/dvclive/live.py:427, in Live.__exit__(self, exc_type, exc_val, exc_tb)
    425 def __exit__(self, exc_type, exc_val, exc_tb):
    426     self._inside_with = False
--> 427     self.end()

File ~/micromamba/envs/haa-segmentation/lib/python3.10/site-packages/dvclive/live.py:399, in Live.end(self)
    396 from dvc.exceptions import DvcException
    398 try:
--> 399     self._experiment_rev = self._dvc_repo.experiments.save(
    400         name=self._exp_name, include_untracked=self.dir, force=True
    401     )
    402 except DvcException as e:
    403     logger.warning(f"Failed to save experiment:\n{e}")

File ~/micromamba/envs/haa-segmentation/lib/python3.10/site-packages/dvc/repo/experiments/__init__.py:471, in Experiments.save(self, *args, **kwargs)
    468 def save(self, *args, **kwargs):
    469     from dvc.repo.experiments.save import save
--> 471     return save(self.repo, *args, **kwargs)

File ~/micromamba/envs/haa-segmentation/lib/python3.10/site-packages/dvc/repo/experiments/save.py:64, in save(repo, name, force, include_untracked)
     62 _, _, untracked = repo.scm.status()
     63 if include_untracked:
---> 64     spec = PathSpec.from_lines("gitwildmatch", include_untracked)
     65     untracked = [file for file in untracked if not spec.match_file(file)]
     66 if untracked:

File ~/micromamba/envs/haa-segmentation/lib/python3.10/site-packages/pathspec/pathspec.py:127, in PathSpec.from_lines(cls, pattern_factory, lines)
    124         raise TypeError(f"pattern_factory:{pattern_factory!r} is not callable.")
    126 if not _is_iterable(lines):
--> 127         raise TypeError(f"lines:{lines!r} is not an iterable.")
    129 patterns = [pattern_factory(line) for line in lines if line]
    130 return cls(patterns)

TypeError: lines:'temp/dvctest4' is not an iterable.
```

I also tried leaving `dir` empty but still the same, just insted of my path there is:

`TypeError: lines:'dvclive' is not an iterable.`

**Comment by daavoo** [comment]
> I tried again on my linux server but unfortunately I get this error:

The last DVC version broke how we use `save_dvc_exp`. I am making a new release DVCLive to fix it.

**Comment by Jarartur** [comment]
Fantastic, downloaded the new version and it works.

Thanks very much for the support 😊.
