### ISSUE TITLE
callbacks: when to call live.end

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvclive#487]
When combining callbacks with post-callback dvclive calls, it may cause unexpected behavior:

* https://github.com/shcheklein/hackathon/pull/9
* https://github.com/erykml/cats_vs_dogs_classification/pull/1

We don't document the context manager along with the callbacks, but it currently seems necessary if making post-callback dvclive calls. When should `live.end` be called? Should we recommend the context manager even when using callbacks?

**Comment by daavoo** [comment]
> Should we recommend the context manager even when using callbacks?

Yes. Let's have this in mind in any future content. We should try to use it anywhere

For all the framework pages in the docs, we now have an example using context manager.
In the [example-get-started-experiments notebook](https://github.com/iterative/example-get-started-experiments/blob/main/notebooks/TrainSegModel.ipynb), we also use context manager + callback.
 
Closing this issue and let's open new ones in docs / example-repos-dev if/when needed.
