### ISSUE TITLE
integrations: sklearn

### ISSUE THREAD

**Issue by pared** [iterative/dvclive#5]
Seems we should be supporting at least few popular frameworks.

Considering their popularity, we should probably start with:
- [x] keras - we have initial implementation
- [x] ~~sklearn~~
- [x] xgboost

Worth considering:
- [x] - ~FastAi~ - #136 
- [x] - pytorch lightning

`TF` and `PyTorch` - it seems to me that using their pure form is done when users need highly custom models, and probably in that cases they will be able to handle `dvclive` by hand.
@dmpetrov did I miss some popular framework?

EDIT:
crossing out FastAi as it has its own issue now

**Comment by pared** [comment]
@dberenbaum Yes, after digging through documentation, it seems to me that in general, learning algorithms divide to those which utilize `fit` method and both `fit` and `partial_fit`. It does not seem to me that we can provide integration for "only `fit`" models, and in case of `partial_fit` models, the workflow will probably look more like `torch` one, which in my opinion does not require any integration, as its created manually.

The only place I could probably see some integration is methods accepting `scoring` param which can be `Callable` but it seems to me it would be really hard to define how such integration could work.

**Comment by daavoo** [comment]
I am considering to work on the integration with `pytorch-lightning` but I'm not sure about where to contribute the new logger (i.e. this repository or `pytorch-lightning` itself). See https://github.com/iterative/dvclive/issues/70#issuecomment-811868255

**Comment by daavoo** [comment]
I added an integration with [mmcv](https://github.com/open-mmlab/mmcv):

https://github.com/open-mmlab/mmcv/pull/1075

**Comment by pared** [comment]
@daavoo Thats a great news! Can we do something to help with that pull request?

**Comment by daavoo** [comment]
> @daavoo Thats a great news! Can we do something to help with that pull request?

It has been already approved so I think it will be merged soon, thanks!

**Comment by daavoo** [comment]
I think it might be a good idea to have separated issues for each integration in order to better track the progress and have specific discussions for each one. 

I.e: https://github.com/iterative/dvclive/issues/83

**Comment by pared** [comment]
@daavoo  That is right, in the beggining we intended it to be an umbrella issue, since singular implementations seemed like easy tasks. As `sklerarn` example shows, we should probably track each integration separately.

For future reference:
Changing the name of the issue for `sklearn`. Other integrations issues should be created as separate issues.
