### ISSUE TITLE
Introduce default directory

### ISSUE THREAD

**Issue by dmpetrov** [iterative/dvclive#51]
```
dvclive.error.InitializationError: Initialization error - call `dvclive.init()` before `dvclive.log()`
```

Why don't we use a default dir if it is not set up explicitly?

**Comment by pared** [comment]
Reopening, clearly the fix did not do a trick, since we discuss in https://github.com/iterative/dvc/discussions/5614 what to do when logs dir is not initialized. cc @dberenbaum
