### ISSUE TITLE
Improve `README` since `dvclive` becomes more important

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvclive#524]
Since `dvclive` becomes more and more an entry point to the ecosystem I think it worth mentioning/show-casing Studio / VS Code and may be even some basic quick start / templates / example repos.

**Comment by daavoo** [comment]
I will start by adding the `Quickstart` in https://github.com/iterative/dvclive/pull/528 to a Colab notebook

**Comment by daavoo** [comment]
> I will start by adding the `Quickstart` in #528 to a Colab notebook

Added a little more realistic example (adapted from `vscode-dvc-demo`) in https://github.com/iterative/dvclive/pull/530
