### ISSUE TITLE
dvc: random order in html

### ISSUE THREAD

**Issue by dmpetrov** [iterative/dvclive#53]
If I regenerate html periodically during the training I'm getting random order of the plots.

The order should be stable and ideally, the same as the reporting order and metrics diff output order.

![image](https://user-images.githubusercontent.com/10081867/108452369-3a242f00-721d-11eb-92de-e70a4504bcd3.png)

**Comment by pared** [comment]
We tried to reproduce this, so far with no result. Keeping open, maybe someone will stumble upon that and we will be able to reproduce.

**Comment by daavoo** [comment]
I was able to reproduce the bug. It's more on the DVC side as it is related to how `plots_data` is collected with `fs.walk`.
