### ISSUE TITLE
Auto-init DVCLive to enable `save_dvc_exp=True`

### ISSUE THREAD

**Issue by daavoo** [iterative/dvclive#531]
In order to use DVCLive and been able to save DVC Experiments, we require:

- Initialized, non-empty Git repository 
- Initialized DVC repository

With DVCLive having DVC Python API as a required dependency, it might be worth trying to do the operations required to fulfill those requirements. 

We could discuss trying to cover all of the requirements or start with the easiest one: calling `dvc init` under the hood when needed)

**Comment by daavoo** [comment]
Thoughts @dberenbaum @shcheklein ?

**Comment by shcheklein** [comment]
I think it makes sense. I don't see a good reason for not creating `.dvc`. I guess it is needed even if we produce `dvc.yaml` in the `dvclive` directory?

**Comment by dberenbaum** [comment]
I worry a little about adding too much magic to dvclive logic, but I think calling `dvc init` at the root of the repo seems like a reasonable default. I guess if not inside a repo, we would just skip it?

**Comment by daavoo** [comment]
Calling this done with #539 . Don't think we should get into `git init + git commit` for now
