### ISSUE TITLE
Can't connect to Studio without creating a DVC experiment

### ISSUE THREAD

**Issue by haimat** [iterative/dvclive#536]
When I run DVC locally with DVCLive, everything works fine and I can see the live updates in Studio:

```
STUDIO_TOKEN="..." dvc repro -f
```

However, when I run the very same DVC experiment on my GitHub runner, I get the following log message on Github:

```console
WARNING:dvclive:Can't connect to Studio without creating a DVC experiment.
If you have a DVC Pipeline, run it with `dvc exp run`.
If you are using DVCLive alone, use `save_dvc_exp=True`.
```

To start the DVC experiment my GitHub CI workflow looks like this:

```console
# Setup DVC and CML
dvc remote add -d -f aime /dvcdata
dvc config cache.type copy
dvc pull --remote aime
cml ci --fetch-depth 0

# Run DVC experiment
dvc repro --force
dvc push --remote aime
cml pr --squash --skip-ci .
```

Additionally, I get the following message in the GitHub runner log, which I do NOT get when I run the experiment locally:

```console
INFO:dvclive:To run with DVC, add this to /__w/head/head/dvc.yaml:
stages:
  dvclive:
    cmd: <python my_code_file.py my_args>
    deps:
    - <my_code_file.py>
```

Note: I have checked that the GitHub action correctly has the `STUDIO_TOKEN` env var set.

Why do I get this "_dvclive:Can't connect to Studio without creating a DVC experiment._" message on GitHub, but not locally, and what can I do to solve this issue?

Ohh and btw., what is the difference between `dvc exp run` and `dvc repro`?

**Comment by dberenbaum** [comment]
Hi @haimat, I would have to look more closely to know why it's working in one environment but not the other, but have you tried using `dvc exp run` instead of `dvc repro`? It should act as a drop-in replacement that also ensures you are saving the experiment. `dvc exp run` is a newer command the runs the pipeline just like `dvc repro` except that `dvc exp run` also saves the results of each experiment run.

**Comment by haimat** [comment]
@dberenbaum Yes, thanks, that has worked now :+1:
