### ISSUE TITLE
Issue running tests with pytest

### ISSUE THREAD

**Issue by mani2106** [iterative/dvclive#542]
- Which operating system and Python version are you using?
Python 3.8.16, Windows 11

- Which version of this project are you using?
The latest from the repo as of the date that this issue is created
- What did you do?
Tried running the tests as mentioned in the contributor guide
`pytest -v tests`
- What did you expect to see?
Expected to see the test session start
- What did you see instead?
![image](https://user-images.githubusercontent.com/20659733/234035409-ae871f6e-3762-4669-b909-3ab989bee146.png)

I solved this by updating the `pytest-sugar` library to `0.9.6` as [discussed here](https://github.com/Teemu/pytest-sugar/issues/241), changing [this line](https://github.com/iterative/dvclive/blob/main/setup.cfg#L48) in the config would avoid the error for others.

**Comment by daavoo** [comment]
Thanks @mani2106 .
We should not be really pinning the test dependencies to specific versions
