### ISSUE TITLE
Long-running task leads to error in GitHub workflow action

### ISSUE THREAD

**Issue by haimat** [iterative/dvclive#547]
We are using DVCLive in combination with DVC+CML to monitor training runs on our GitHub CI runner. This works fine, however, when the training lasts longer than 24 hours, then at the end of that training we ran in to the following error on GitHub:

> Unable to extend GITHUB_TOKEN expiration time due to: GITHUB_TOKEN has expired.

We assumed this is a typical problem with the GITHUB_TOKEN, since that cannot be used for longer than 24 hours in any GitHub workflow action. However, even when we use a GitHub Personal Access Token (PAT), we still run into the same problem. At the end of the training the runner produces the following stack trace:

```python
 Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/dulwich/file.py", line 147, in __init__
    fd = os.open(
FileExistsError: [Errno 17] File exists: '/__w/micromacro/micromacro/.git/index.lock'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/__w/micromacro/micromacro/src/dvc/yolo-trainer.py", line 77, in <module>
    with Live(report="md") as DVC:
  File "/opt/conda/lib/python3.10/site-packages/dvclive/live.py", line 463, in __exit__
    self.end()
  File "/opt/conda/lib/python3.10/site-packages/dvclive/live.py", line 419, in end
    self._ensure_paths_are_tracked_in_dvc_exp()
  File "/opt/conda/lib/python3.10/site-packages/dvclive/live.py", line 477, in _ensure_paths_are_tracked_in_dvc_exp
    self._dvc_repo.scm.add(paths_to_track)
  File "/opt/conda/lib/python3.10/site-packages/scmrepo/git/__init__.py", line 286, in _backend_func
    result = func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/scmrepo/git/backend/dulwich/__init__.py", line 280, in add
    self.repo.stage(files)
  File "/opt/conda/lib/python3.10/site-packages/dulwich/repo.py", line 1358, in stage
    index.write()
  File "/opt/conda/lib/python3.10/site-packages/dulwich/index.py", line 318, in write
    f = GitFile(self._filename, "wb")
  File "/opt/conda/lib/python3.10/site-packages/dulwich/file.py", line 91, in GitFile
    return _GitFile(filename, mode, bufsize, mask)
  File "/opt/conda/lib/python3.10/site-packages/dulwich/file.py", line 153, in __init__
    raise FileLocked(filename, self._lockfilename) from exc
dulwich.file.FileLocked: ('/__w/micromacro/micromacro/.git/index', '/__w/micromacro/micromacro/.git/index.lock')
```

We thought we could solve this problem with the use of a PAT, but as said, the problem still persists. So this seems to be either a bug with DVCLive, or we are doing something wrong within our GitHub workflow. For your reference, here are the relevant parts of that workflow:

```yaml
jobs:
  train-and-report:
    if: "contains(github.event.head_commit.message, '[TRAIN]')"
    timeout-minutes: 10080  # 1 week
    runs-on: [self-hosted, gpu, cml]      
    # ...
      
    steps:
      # ...
          
      - uses: iterative/setup-cml@v1
        env:
          CML_TOKEN: ${{ secrets.CML_REPO_TOKEN }}  # We store our PAT in CML_REPO_TOKEN
          
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.CML_REPO_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.CML_REPO_TOKEN }}
          STUDIO_TOKEN: ${{ secrets.DVC_STUDIO_TOKEN_MFB }}
          STUDIO_REPO_URL: git@github.com:${{ github.repository }}.git
        run: |
          # ...
          # Run DVC experiment
          dvc exp run --force  # <-- At the end of this it seems the error shown above happens
          dvc push --remote aime
          cml pr --squash --skip-ci .
          # ...
```

What do you think - bug in DVCLive or an issue with our use of a PAT on GitHub?

**Comment by daavoo** [comment]
> What do you think - bug in DVCLive or an issue with our use of a PAT on GitHub?

I am going to try to reproduce.

In the meantime, I might send a patch in DVCLive to catch the exception so it doesn't cause a failure of the whole execution

**Comment by daavoo** [comment]
> @daavoo Did you have any luck reproducing this? At the moment this is a show stopper for us, as we cannot train a model for more than 24 hours, which is necessary for some projects. How do you recommend to run experiments on GitHub for more than 24 hours, with respect to this GITHUB_TOKEN issue?

Sorry @haimat , I haven't yet. 

On the GITHUB_TOKEN, I think there is no workaround but to use a PAT.

I have pushed a new DVCLive release that would hopefully catch the error you were facing.

Could you try using `pip install dvclive == 2.8.1` and a PAT token?

**Comment by daavoo** [comment]
> Clearly I cannot be the first of your users who train for longer than 24 hours, right?!

No real idea 😅 

It might be that because some of the CML functionalities already require a PAT, people already set up that and didn't encounter the "token timeout" related to the default token Github provides 🤷 

I do remember some timeout issues reported, but they were about the runners, which is why in the docs there are explicit mentions and examples on how to extend the default "runner timeout" with `timeout-minutes`:

https://cml.dev/doc/self-hosted-runners#allocating-cloud-compute-resources-with-cml

**Comment by skshetry** [comment]
The traceback looks more like a race condition than the issue with token. DVC is trying to write locally and git's index is locked because of something else is trying to modify the index at the same time. The issue also happens time to time in our dvc tests.

Is that all the traceback?

**Comment by haimat** [comment]
@skshetry Yes, that's the whole traceback. It might be related to the callbacks we use with our YOLOv8 training, don't know for sure though. I could think of the following related steps in our workflow:
 - `dvc_live.next_step()` called at the end of every training epoch
 - `dvc_live.make_dvcyaml()` called at the end of every training epoch ([to avoid this issue](https://github.com/iterative/studio-support/issues/85))
 - `dvc_live.log_image(f, img)` called once at the end of the whole training
 - at the end of the `with dvclive.Live()` block, which encapsulates the whole training

At which point would DVC try to write to the local git index?

**Comment by skshetry** [comment]
Sorry i meant dvclive not dvc. The error is raised at `Live.end()` which means that it is exiting the block successfully or exiting because of an exception. And I don’t see any traceback from that.

**Comment by haimat** [comment]
OK, your last update fixed this issue 👍
