### ISSUE TITLE
`log_plot`: Support path to custom template

### ISSUE THREAD

**Issue by daavoo** [iterative/dvclive#552]
> Yes, do you feel the link doesn't explain/imply it?

> It wasn't clear to me either way -- I genuinely didn't know. I don't think we need to get into it in this PR. It was more of a product question that didn't occur to me until docs review.

> Actually, I think custom templates might be broken as the user would need to pass the path relative to `dvclive/dvc.yaml` in order to work

So in DVCLive, should we do this?

1. Adjust the path to be relative to `dvclive/dvc.yaml`
2. Check that the template exists -- what should we do if not?

_Originally posted by @dberenbaum in https://github.com/iterative/dvc.org/pull/4497#discussion_r1181602414_

**Comment by daavoo** [comment]
@dberenbaum I took a look into this and it just works:

https://github.com/iterative/dvclive/issues/569#issuecomment-1549406286

However, I think it is a problem as it means that DVC is not resolving the custom templates with respect to the `dvc.yaml` (at least for top level plots, didn't test stage level)

**Comment by dberenbaum** [comment]
So it works but shouldn't work basically? So do I have this right?

1. dvclive saves it relative the working dir instead of relative to dvclive/dvc.yaml.
2. dvc resolves it from the repo root or working dir instead of from dvclive/dvc.yaml.
