### ISSUE TITLE
`log_image`: Support tracking with DVC.

### ISSUE THREAD

**Issue by daavoo** [iterative/dvclive#568]
The `dvclive/images` folder can quickly become large enough to not be tracked by Git.

The generated `dvclive/dvc.yaml` uses top-level plot definitions that are only descriptive (used for collection) but can't enable DVC caching.

**Comment by dberenbaum** [comment]
Maybe`log_image` can have a flag like `cache=True` that does the `dvc add` (similar to what `log_artifact` does)?

**Comment by dberenbaum** [comment]
So we can either:

1. Cache the entire image folder, which is clean and simple. Would we need a flag to enable/disable it? Would we do the same for other folders like custom plots?
2. Cache individual images, which create lots of dvc files but gives granular control, can be enabled/disabled with a flag like `log_image(cache=True)`, and can be easily extended to any other methods/output types. Is it too messy to keep individual dvc files?

**Comment by shcheklein** [comment]
I think we need to cache the whole folder with an option.

**Comment by dberenbaum** [comment]
What if we have `Live(cache=["plots/images"])` to specify which paths to cache? I think it will be breaking to start caching in a minor version, but we could make this the default in the next major version.

**Comment by shcheklein** [comment]
May be something higher level? `Live(cache_images=True)`? 

Or even - use_cache (that would trigger it for artifacts and images) - since if I cache a model, I'm fine tbh to cache images (and most likely that what I want).

**Comment by dberenbaum** [comment]
My concern is that I can imagine users will sometimes want to track images, sometimes, artifacts, sometimes other plots or output types, so I'm trying to think of how to make it both easy and flexible. I also think for now that caching anything by default raises the barrier to entry since you likely need to configure a remote and understand dvc caching and storage.

**Comment by shcheklein** [comment]
> I also think for now that caching anything by default raises the barrier to entry since you likely need to configure a remote and understand dvc caching and storage.

yes, but how realistic is that you don't have to do that? even on a simpler project?

**Comment by dberenbaum** [comment]
Good question. Anyway, if I'm overcomplicating, happy to start with a `cache_images` option.

**Comment by shcheklein** [comment]
sounds good, Dave.
