### ISSUE TITLE
Add support for arbitrary Vega-Lite plots

### ISSUE THREAD

**Issue by alexk101** [iterative/dvclive#569]
I am not entirely sure that this is a possible feature , as I feel it would have already been implemented if that were the case, but it would be nice to log any kind of vega-lite plot. Currently there exists the `log_plot`, but this is fairly limited by the requirements of DVC plot templates. For example, if I wanted to create a grouped bar plot, I could not with the current way in which values are injected.

```json
{
  "title": {
    "text": "Classification Metrics",
    "anchor": "middle"
  },
  "encoding": {
    "column": {
      "field": "category",
      "header": {
        "orient": "bottom"
      }
    },
    "y": {
      "field": "macroF1",
      "type": "quantitative"
    },
    "x": {
      "field": "group",
      "axis": null
    },
    "color": {
      "field": "group"
    }
  },
  "config": {
    "view": {
      "stroke": "transparent"
    }
  },
  "mark": "bar",
  "data": {
    "values": [
      {
        "category": "feedback",
        "group": "deck",
        "macroF1": 0.2513221334131033
      },
      {
        "category": "feedback",
        "group": "deck shift",
        "macroF1": 0.250825352553961
      },
      {
        "category": "feedback",
        "group": "earliest quint",
        "macroF1": 0.204823556791436
      },
      {
        "category": "planning",
        "group": "deck",
        "macroF1": 0.2513221334131033
      },
      {
        "category": "planning",
        "group": "deck shift",
        "macroF1": 0.250825352553961
      },
      {
        "category": "planning",
        "group": "earliest quint",
        "macroF1": 0.204823556791436
      },
    ]
  }
}
```

[This](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQmOoLhpQmOAA9MaEAGFBSCBBoAzGlCQq5AAgCycTACcrERSCSzYbF-oQaABMgtRAAXyU4HzYgmlkyDRAoNkEGBHlUUEs4QSD9ay0yPwBPT3gkILh-LJA-Gmi9dCY2bDYECMiQMtqcvICkKBc2ADEARk9MEpx1dABHBm8VTBsaUgilbSS+-PQyYYYcTyRtGg9UWQZBQS6UwT9thv69g6Pw27lLRNriBoB3JIQVxsADWs2ULm8EBwSBcjU6SmQLhB+iYsM8QRsKB+SDScHOAG1QIVyKV9OY4HAgmioCilPs2Id9FVaZ5kENRhNUAAGSgAJjEYwAzHy+cKhQAWYVjblCoWRYk2UkuHogClUml0kAMpnoFkguwQGAWPSIwbDcZoXkC7kADgFQrEArEQoAnAA2MYK5JK4oq8mU6mDLU6o7oOCw4T4zB2BbxU0gdkWrnW7kS+2OsTugDsrrGEqF7u9JL9qpwxlksniiXpr2ZcFZZo5lp5-MFIrFcqlQplcuLvrJ6HL3irCU8ofrtMNxvMCaTnKtbbtDqdYhdHq9CkVRUHIGHler47r4cjDSBsYY8bZ5oXrb5aYza5zeYLRYAuu8gA) is a live view of the above plot. It may be the case that it is more appropriate to submit this as an issue on DVC, and not DVCLive, but I will put it here for now.

**Comment by daavoo** [comment]
Hi @alexk101 , it is a little hidden in the docs, but it is possible to use custom vega templates in DVC as described in https://dvc.org/doc/command-reference/plots/templates#custom-templates .

So, for your example, the custom template would look as follows:

```json
{
    "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
    "data": {
        "values": "<DVC_METRIC_DATA>"
    },
    "title": {"text": "<DVC_METRIC_TITLE>", "anchor": "middle"},
    "encoding": {
      "column": {"field": "category", "header": {"orient": "bottom"}},
      "y": {"field": "<DVC_METRIC_Y>", "type": "quantitative"},
      "x": {"field": "<DVC_METRIC_X>", "axis": null},
      "color": {"field": "<DVC_METRIC_X>"}
    },
    "config": {"view": {"stroke": "transparent"}},
    "mark": "bar"
}
```

Assuming it is saved in `custom_template.json`, you could reference it in your Python code:

```py
from dvclive import Live

datapoints = [
    {"category": "feedback", "group": "deck", "macroF1": 0.2513221334131033},
    {
      "category": "feedback",
      "group": "deck shift",
      "macroF1": 0.250825352553961
    },
    {
      "category": "feedback",
      "group": "earliest quint",
      "macroF1": 0.204823556791436
    },
    {"category": "planning", "group": "deck", "macroF1": 0.2513221334131033},
    {
      "category": "planning",
      "group": "deck shift",
      "macroF1": 0.250825352553961
    },
    {
      "category": "planning",
      "group": "earliest quint",
      "macroF1": 0.204823556791436
    }
]

with Live(report=None) as live:
    live.log_plot(
        "custom_bar_plot", 
        datapoints, 
        x="group", y="macroF1", template="custom_template.json",
        title="Classification Metrics"
    )
```

And the plot should be rendered correctly:

```console
$ dvc plots show
```

![visualization](https://github.com/iterative/dvclive/assets/12677733/a7b57146-10a8-42e1-be28-7720972e7c71)

**Comment by alexk101** [comment]
Ah, I see. My understanding of the parameters and how they are injected was a little off. This solves my problem. Thanks, @daavoo ! And I see this other issue you have added and agree with your points there.

**Comment by alexk101** [comment]
I seem to have found another sticking point for my work. Does DVC not support the 'spec' field for vega lite? I am trying to do something similar to what I previously posted, but using a faceted plot.

```json
{
    "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
    "repeat": ["quintile"],
    "config": {"view": {"stroke": "transparent"}},
    "spec": {
        "title": {"text": "<DVC_METRIC_TITLE>", "anchor": "middle"},
        "encoding": {
            "column": {"field": "category", "header": {"orient": "bottom"}},
            "row": {"field": "quintile", "title": "Quintile"},
            "y": {"field": "<DVC_METRIC_Y>", "type": "quantitative"},
            "x": {"field": "<DVC_METRIC_X>", "axis": null},
            "color": {"field": "<DVC_METRIC_X>"}
            },
        "mark": "bar",
        "data": {
            "values": "<DVC_METRIC_DATA>"
        }
    }
}
```

The structure of the plot is valid, as I have it displayed in the vega-lite editor [here](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAJzg44STGgDaIAI4MaszDUFwQAXSVQ5AMxpk0oYjTgB3JyAiZlbANbm6D5IshA4SKrGIAC+0UphcFCeJphmyXAAHlroAMKCSBAQNPZQmuyyAAQAsnA+NFAQiiAhsGzKaCAINAAm3WlxIHCyNt1GjqigNoIMCPITIPZwgt0dpZjkbQCeTfBI3XDt822uUehMbNhsCDEDvh7zi8sdBkYmaUopaegAiobGpuYBtsHq4nuhkFBfAAxACMTUwm3UzwYIRSZVIMSUGU8jxW6DIvgYOCaSAyNEaqFkDEEggGUzaONBeJABLYRJuSmQyj8HSYESa3U0KHmxCQ0zgFO0k00G2UwIWcDg3T5UB5SlZ7PQ+1VTQh0LhqAADJQAExiGEAZhNJstFoALJaYYaLRalC9-l99HC4tL1mQth1bIrlUgderCcStYk1Z1Q-q0MazZbrbaHRanS63X83oF9CbMb7ZfKg0qVTGNZGQNqY3q2LCE6bzVabS60xnXfpswDnhaCyA1kXA8Gy00Kx1q7q43WDYmmynW47nR33Tnnna+wP-XKh6XQ+WI+Po5PIdOG0nm6nF5nO69u+g9GINzKt8Xh3vRweo6qKhAYMUtJyU71kajaGgAHGaFpiGaYgWgAnAAbDCWa3p6ejegohYvjuIZhiyn5VtGP5-rYAGxiewGzuBkHQWIsGIchN4ermej5j6-bPgG6Alrh+5spW1bEf+x7xiBZrUbBtH0UhKHMT2T5+lxCq7nhY5fn4QmkSJp5iWIElQTB8EyUxq73uu7GbkpPEjuG-GHt+v7CYBFEzqBEGSYZDGyaZ+iPhZnHbtxb6qQRGjKMIEqYBUK7aZRpqGnaEFQWICEAOxwTCdoWgh3l3l6CmDkFKl8ZqgwRBF3jRdmsWuSaCVJXRaUZVlOUmXlrEFdhRW8R+dnoGFFVRTFzmiYm9UmslTWZdluVob2-mKYFyk9bZpUDa4lXDeRo3xYlE2Nel02tSu7XmZhHGLa+xW9Wt5UbUN1UjTpY17ZNh0tbNLF+edllLdZ76rZWsi1BUFBGDVDYpYaYhgYahomnBE0mmBH1tWhGFYVZwUlUDINg-IT1xVDMNwwjSMozNaMsWxP0BVdK34X1IDA1F+MQyBxOw-DiNWhTx1dnNnVY9dgMdCzoNIODhOuZzpM88jqMnWhZ2Y392M3bjrOSwT23PZQsvc+TisC19QtqyLjOlWYESyGM7PGghDoK3a6VgXB2XQXan3PBjF2FctNmW5W1vKLbsiONLDaOzCzuu+7CGe979406r9OB2pIAh2HEe63F0ex3BbseyaXtU-JC3+-9IVM1nduRyB+coy7hfx4nZdmWbacA0HHS1+H9uUI3drN0XCcl0nvmdx0OD5LI2ca-ZNZAbV8FZYaGZmsPzrIxP6FT+gM8hPPovqQPE1wWvG9iFvvO7ynftdSAh9z3XPen-Xiarxa6-b9fdrb2BXe81aaXWnrPY+b9CJ4VrHFc+l9f43x3u3fQKsH5KWfhAjOE4P6mi-j-K0f8AG72+qnMBR9X5YKIo5LSOCS4k3TAnVKDoHQIUAcgveFdH4YIoQRQS1CyIwNqnaehMJGHMNEWwpW1N95P3ATwpmfCSICOXmeYRsMGFiCYZlCRQCZHcP7ifKBGl+FnzUc6URmjxGsN3qg368p9E50oQ5JRpiRFiO0dY9hJC0FLQcQvfqd1IpVVeGfOGS53YXxNAhKC69Uq719nYshL8DGQPWkEragizxhJdBEu0USYkwjiew++iSD5yJSRnNJm1Hq51qtk+Cq98l6UKbozh6DymONCoE6pITaH1NyU02JNi9EdP8WVcK91glRD6XDHJjTonNKKVI543jSmyPIRUgi4s2Y4L0oaRGETEJgRjnBVKYh4kjI2Z0pm2ztYDz2Qc+CRyTlnLvpc5J1zSq3KlrUyGcNHlwWeQjV57DgGkLKVcsZ3ydaZI5v8hGTzWEvPOew2xdMkmYK2XjO5uz4WHKRcClFyz7yrPRRCj5Yy+451hQ7FK84spgVSlBQpkiTY+3eZimuYUIE0sHnSlsDKmXmlSqy1C0i2m+NGYYqlA8E4IXpRaRlzKRWtJAf7Px0ruWv15XKhVSrhWirkh3CV9ipWQJlTg3VArFVCpZcQmRfIIBLCMOYQx2DfliRdAhQ0qUS7r1YRBN2pdiX5RNbyAozrgZjPdbyia2UfV+okYGi+byw1nAjcIKNbqjy0K9Qm-+SbkYptBQ6jNLro05o9Z-eNvqC0BqLcGtlxq1WP0dZG11kCY0qM9TWxN9ag32rTSANtmaO1OOMS42hCF5UmlStO2GyMSZpQuUOkd5bs3OKclW0007rRztYfDMCS6llNrzKWp1o6K2bpoduqJM790LqPbDZdJbV1lqzZ2qhk7b27tnfOw9x7hlvoveuz917lEuTPL+h9AHn0nrFSs897axlVIer029+zGVNWhmlF2TKV0tqUmuj9lTuloemRhwuc70o4aYalfDxSkOXsMahqZEGdp1So9hlKdGGMhr0GCnx8piNjq6RM9JNTY2Yeo3BWjeHlynr0Gi0B6aQMkbE4NNjoSuM0Z4-JwdhGloiahdin5vK7SOwdAcmEliUoxwI+C4d77RM3NMzC7txoLPDxhNZ2zSETSpsM8J5zJmtZmY85QLzVmEY2aYXZgLr6gvhrUy5r5bmB5RZ8zFvz9nUVMdAxnaFGXLNZYyjlhL-HSUqacylylWqUm8ovjDdM4FUqFOiR7BzQnkvIc1TbbVEWmtgRa4y9rXqiWKZKWSmrvXzX1epYNtRI22tzvG6qxzxm+uhwG5BkCQ3ltjc63l4Ds2M4Wu3ftp0o3VtHcqzECwsRohAA). When I try and plot this using DVCLive, it tells me that I am missing the '<DVC_METRIC_DATA'> anchor,

```
dvc_render.vega_templates.BadTemplateError: Template '../templates/multi_bar_summary.json' is not using '<DVC_METRIC_DATA>' anchor
```

 though I am clearly including it. Is this some kind of issue with how templates are parsed or am I missing something else?

**Comment by dberenbaum** [comment]
@alexk101 Can you provide the output of `dvc doctor`? I'm able to generate a plot with that template:

![visualization(4)](https://github.com/iterative/dvclive/assets/2308172/baaa64f4-e6cf-4f26-814b-c61279fedeed)

**Comment by dberenbaum** [comment]
Okay, now I think I have the right template and it's working. Could you try `pip install --upgrade dvc dvclive dvc-render`?

![visualization(6)](https://github.com/iterative/dvclive/assets/2308172/186d55c1-681e-422d-80f1-d99b4c79987d)

**Comment by alexk101** [comment]
@dberenbaum Unfortunately still failing, though somewhere else now.

Stacktrace:
```
Traceback (most recent call last):
  File "/home/alexk101/Documents/Research/Bertenthal Lab/igt/igt-models/src/summarize.py", line 126, in <module>
    sys.exit(main())
  File "/home/alexk101/Documents/Research/Bertenthal Lab/igt/igt-models/src/summarize.py", line 119, in main
    summarize()
  File "/home/alexk101/Documents/Research/Bertenthal Lab/igt/igt-models/src/summarize.py", line 113, in summarize
    with Live(str(Path('../summary'))) as live:
  File "/home/alexk101/.mambaforge/envs/general/lib/python3.10/site-packages/dvclive/live.py", line 521, in __exit__
    self.end()
  File "/home/alexk101/.mambaforge/envs/general/lib/python3.10/site-packages/dvclive/live.py", line 499, in end
    self.make_report()
  File "/home/alexk101/.mambaforge/envs/general/lib/python3.10/site-packages/dvclive/live.py", line 462, in make_report
    make_report(self)
  File "/home/alexk101/.mambaforge/envs/general/lib/python3.10/site-packages/dvclive/report.py", line 173, in make_report
    render_html(renderers, live.report_file, refresh_seconds=5)
  File "/home/alexk101/.mambaforge/envs/general/lib/python3.10/site-packages/dvc_render/html.py", line 99, in render_html
    document.with_element(renderer.generate_html(html_path=output_path))
  File "/home/alexk101/.mambaforge/envs/general/lib/python3.10/site-packages/dvc_render/base.py", line 54, in generate_html
    partial = self.partial_html(html_path=html_path)
  File "/home/alexk101/.mambaforge/envs/general/lib/python3.10/site-packages/dvc_render/vega.py", line 94, in partial_html
    return self.get_filled_template()  # type: ignore
  File "/home/alexk101/.mambaforge/envs/general/lib/python3.10/site-packages/dvc_render/vega.py", line 78, in get_filled_template
    if not self.template.has_anchor(name):
  File "/home/alexk101/.mambaforge/envs/general/lib/python3.10/site-packages/dvc_render/vega_templates.py", line 123, in has_anchor
    found = dict_find_value(self.content, self.anchor(name))
  File "/home/alexk101/.mambaforge/envs/general/lib/python3.10/site-packages/dvc_render/vega_templates.py", line 73, in dict_find_value
    return any(dict_find_value(e, value) for e in v)
  File "/home/alexk101/.mambaforge/envs/general/lib/python3.10/site-packages/dvc_render/vega_templates.py", line 73, in <genexpr>
    return any(dict_find_value(e, value) for e in v)
  File "/home/alexk101/.mambaforge/envs/general/lib/python3.10/site-packages/dvc_render/vega_templates.py", line 65, in dict_find_value
    for v in d.values():
AttributeError: 'str' object has no attribute 'values'
```

DVC Doctor:
```
DVC version: 2.57.2 (pip)
-------------------------
Platform: Python 3.10.11 on Linux-6.3.2-arch1-1-x86_64-with-glibc2.37
Subprojects:
	dvc_data = 0.51.0
	dvc_objects = 0.22.0
	dvc_render = 0.5.2
	dvc_task = 0.2.1
	scmrepo = 1.0.3
Supports:
	http (aiohttp = 3.7.4.post0, aiohttp-retry = 2.8.3),
	https (aiohttp = 3.7.4.post0, aiohttp-retry = 2.8.3),
	ssh (sshfs = 2023.4.1)
Config:
	Global: /home/alexk101/.config/dvc
	System: /etc/xdg/dvc
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/nvme0n1p7
Caches: local
Remotes: ssh
Workspace directory: ext4 on /dev/nvme0n1p7
Repo: dvc, git
Repo.site_cache_dir: /var/tmp/dvc/repo/140d32e21af9cdc540ba90f3896b4725
```

It seems to be getting stuck parsing the some part of the template that should be a dictionary, but is a string.

**Comment by alexk101** [comment]
I found where the problem in dvc-render is. I am opening a pull request for the change. Will update when I am done.

**Comment by alexk101** [comment]
https://github.com/iterative/dvc-render/pull/134

**Comment by dberenbaum** [comment]
Nice, thank you for finding that bug! Sorry, I guess it was me who was using the outdated version 🤦 .

**Comment by daavoo** [comment]
I think we can close this one and if something else comes up, open a new one here or in dvc-render.

Thanks @alexk101 !!
