### ISSUE TITLE
`summary`: split names into nested dict automatically

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvclive#574]
```python
live.summary[metric] = value
```

should have the same semnatics as `live.log_metric(metric)` except skipping the plots part.

It means we should split the metric name by `/` (`os.sep`) as we do in `log_metric`.

Btw, why do we use `os.sep` to split metric names? Are they usually platform dependent?

**Comment by daavoo** [comment]
> should have the same semnatics as live.log_metric(metric) except skipping the plots part.

No strong opinion but not sure about this. `live.summary` is just a plain Python dictionary and was meant to be manually manipulated as-is, like:

```py
live.summary["train"]["foo"] = 2
live.summary["train"]["foo"] = {"bar": 1, "goo": 3}
```

> Btw, why do we use os.sep to split metric names? Are they usually platform dependent?

It doesn't matter because the split is called on `normpath` result, but it is probably unnecessary and could be replaced by a split on slash.

**Comment by shcheklein** [comment]
> No strong opinion but not sure about this. live.summary is just a plain Python dictionary and was meant to be manually manipulated as-is, like:

Yep, I know. Thus may be it can be "log_metric(something, summary=True)"? 

Otherwise, I ended up writing the logic myself:

https://github.com/shcheklein/ultralytics/blob/94072007c6ca7a6bb19f57c0a62280d71ce2f203/ultralytics/yolo/utils/callbacks/dvc.py#L114-L118

It runs at the end the best model one more time and saves the best metrics instead of the last ones. There are two options - duplicate all the metrics (last + best) or overwrite. I'm following the framework which prioritizes the best metrics (and I think it makes sense to operate with the best model + best metrics tbh).

**Comment by daavoo** [comment]
> Yep, I know. Thus may be it can be `log_metric(something, summary=True)` or `log_summary` call?
> 
> Otherwise, I ended up writing the logic myself:
> 
> https://github.com/shcheklein/ultralytics/blob/94072007c6ca7a6bb19f57c0a62280d71ce2f203/ultralytics/yolo/utils/callbacks/dvc.py#L114-L118

I see. WDYT of `log_metric(something, plot=False)`? Do you think is more clear or more confusing?

> It runs at the end the best model one more time and saves the best metrics instead of the last ones. There are two options - duplicate all the metrics (last + best) or overwrite. I'm following the framework which prioritizes the best metrics (and I think it makes sense to operate with the best model + best metrics tbh).

This seems to go back to #89

**Comment by shcheklein** [comment]
> I see. WDYT of log_metric(something, plot=False)? Do you think is more clear or more confusing?

I think that is fine as well. I don't see that much difference.

**Comment by shcheklein** [comment]
@dberenbaum could you please summarize please, what was the issue - performance, product?

**Comment by dberenbaum** [comment]
@shcheklein It was a product issue that users didn't always expect that behavior. You only need to read the OP in that issue, specifically:

>     * The training metrics I am logging in PyTorch Lightning seem to be getting incorrectly grouped. For example, in the produced metrics.json, my 'val_model_error' metric is parsed into:
> 
> 
> ```json
> "val": {
>         "error": {
>             "model": 0.1
>         }
> }
> ```

**Comment by dberenbaum** [comment]
> This seems to go back to #89

Relevant proposal from #89 

>  A single defined objective for the summary like `live.make_summary(objective="loss", keep="min")`. The difference here is that DVCLive would find the step with the min loss and keep all metrics from that step in `metrics.json`.
>
> we could also put these arguments into the init method like `Live(objective="loss", keep="min")` and then pass them to `make_summary`.

The benefit of that approach IMHO would be that it is closer to the user workflow, whereas `log_metric(summary=True)` or `log_metric(plot=False)` feel more like they ask the user to know all the mechanics of dvclive.

**Comment by daavoo** [comment]
> Especially per metric. At least I don't know how do it.

We can just copy wandb API, which has an explicit `define_meric` methid for that

**Comment by dberenbaum** [comment]
Okay, I misunderstood, I think it's related but not the same as #89. In #89 (like what @daavoo mentions for wandb), where you want to save the best of the metrics you already have, and you only need to define a single metric that controls what is "best" (so dvclive would look up the min value of loss and then take the acc and other metrics from that same step).

It looks like for yolo, it is running some new validation step on a prior model checkpoint, so these metrics may not even exist in a previous step, right?

**Comment by shcheklein** [comment]
> It looks like for yolo, it is running some new validation step on a prior model checkpoint, so these metrics may not even exist in a previous step, right?

yes. they probably exist, but there is not simple way connect them back. Plus the rule for the best can be tricky (they have some "fitness" score inside, that is probably not even published as a metric - I can check that).

**Comment by dberenbaum** [comment]
> `log_metric(something, plot=False)`

👍
