### ISSUE TITLE
Set exp name

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvclive#582]
Can we also add exp name? Seems odd to me that we have support for message but not name.

_Originally posted by @dberenbaum in https://github.com/iterative/dvclive/issues/565#issuecomment-1551350667_

**Comment by VladVin** [comment]
I'm also interested in having an experiment name parameter for the `Live` class. At the moment, the experiment name is always set at random string. Isn't it the `prefix` parameter that should do the job?
