### ISSUE TITLE
Should the `dvc stage add --live <path>` arg override `init(path)`?

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvclive#60]
It's more of an idea for `dvc stage add` but I thought I'd ask here first (we can transfer the issue if needed).

If you call `dvc.init()` manually, `path` is always required. So in those cases, combined with using DVC, you have to match `path` with the arg. of `dvc stage add --live`. Seems error-prone.

The arg to `--live` could be optional. If there's no `init()` call in code, ~~then DVC would need to give an error~~

UPDATE: Calling `init()` is no longer required though, as DVCLive has a default `path` for its outputs now.

Thoughts?

**Comment by pared** [comment]
So, currently our integration is that we can provide `--live` to dvc, which will pass the information down to the code. Do I understand correctly that here we would make this process "in reverse"? If there is `dvclive.init` call, ping the DVC to add `live` output to currently executed stage? So that user does not even have to use `dvc run --live` or `dvc stage add` to mark `live`?

**Comment by jorgeorpinel** [comment]
Not exactly. I'm suggesting that if there's an `init('path')` call in the code then there's no need for `stage add --list` to get an argument. Requiring it in that case means that if you don't use the exact `path` as in the code, there will be some sort of error anyway — what's the error text BTW?

I was thinking that the `--live` argument could be optional and DVC could error out if there's no `path` in the code instead (during `repro`). But now that I think about it that's probably even more complicated U (harder to handle errors).

What about keeping the `--live <path>` arg required, but have that override whatever is defined in `init()`? With a warning

**Comment by pared** [comment]
> What about keeping the --live <path> arg required, but have that override whatever is defined in init()? With a warning

@jorgeorpinel I think it makes sense. I was actually considering creating an issue with making `init` call required even when we are using `dvc`. The problem that not requiring `init` introduces is that in such case, we can execute the code only if we are doing it in `dvc` context. We would be unable to successfully run `python train.py` if there is no `init` call, which leads us to an unprecedented situation where `dvc` is required to run the training script.

cc @dberenbaum

**Comment by jorgeorpinel** [comment]
> considering creating an issue with making init call required even when we are using dvc

What will happen to `stage add --live` in that case?

**Comment by dberenbaum** [comment]
@jorgeorpinel See https://github.com/iterative/dvc/issues/5606. I'm hoping it can go away, but interested to hear what @pared thinks.

**Comment by pared** [comment]
@jorgeorpinel I created PR that basically gives priority to DVC config over "in code" config: if we detect DVC env variables, and they are different that current config set up with `init` we provide new logger.

**Comment by dberenbaum** [comment]
Is this the desired behavior, or is it better to throw an error? It seems like it could be confusing for users to have values that don't match. Is there a use case where someone would want to have different values in each and have `dvc.yaml` override `dvclive.init()`?

**Comment by pared** [comment]
@dberenbaum I think, besides the use case where one forgets to remove `init` from code it does not make too much sense. 
And thanks to #67 We have covered the situation where one could not run the code without dvc. This PR makes the behavior consistient with the one implemented in #67, but besides that, there is not much that it would provide.

**Comment by dberenbaum** [comment]
Okay, it seems reasonable to me to throw an error if the paths conflict, but I'm fine with an override if you and @jorgeorpinel think it makes more sense, as long as it's documented.

**Comment by jorgeorpinel** [comment]
> PR that basically gives priority to DVC config over "in code" config

OK, thanks! Will check it out.

> if we detect DVC env variables...

I'm a bit confused as to how env vars relate to this. From what I remember the ways to set this up were a) via `dvclive` code (`init()`) or via `dvc stage add --live`. Will check the PR... ⌛

**Comment by jorgeorpinel** [comment]
> is it better to throw an error? could be confusing for users to have values that don't match

@dberenbaum can you clarify what values wouldn't match what? Sorry, this one is confusing (especially now after some time has past).

> use case where someone would want to have different values in each and have dvc.yaml override dvclive.init()

Same here — have different values in each what? Just making sure I get understand you questions.

Thanks

**Comment by jorgeorpinel** [comment]
p.s. comment about warning vs question, in case it helps: https://github.com/iterative/dvclive/issues/60#issuecomment-794915809

**Comment by jorgeorpinel** [comment]
> I'm a bit confused as to what env vars we're talking about

OK so I checked https://github.com/iterative/dvclive/pull/74#pullrequestreview-662763978 and I'm still not sure how it addresses this issue. Putting env vars aside, `dvc.init()` still requires `path`, and when using DVC you still have to match it with the `live` field of dvc.yaml, right? (or is it going away per #5614?)

Maybe we should move this to the DVC repo and discuss https://github.com/iterative/dvclive/issues/60#issuecomment-843145554 about env vars behavior in #74. Or am I totally confuse here? 🙂

**Comment by jorgeorpinel** [comment]
> I was actually considering creating an issue with making init call required even when we are using dvc

BTW is there a separate issue to track this or has it been done in some PR? Thanks

**Comment by jorgeorpinel** [comment]
> when dvc provides --live option for stage/run, it is equivalent to setting the environmental variables

Ah, so DVC literally sets those env vars (based on the `live` field in dvc.yaml) during exp runs. I see...

> This change (#74) shows how we could ... use those values to initialize the dvclive even if there was dvclive.init call
what I am trying to push in this change is overcomplicated and confusing

Hmm no I was just unaware of the mechanism in which DVC and Dvclive communicate. It makes sense now. `stage add --live <path>` i.e. the `live` field in dvc.yaml (which is communicated via env vars) would now override `dvclive.init()` config. Addresses this issue directly 👍

**Comment by jorgeorpinel** [comment]
> I think that if init is called in code, we should check if config matches what dvc provides and throw if not.

Having some sort of messaging so we make sure the user is aware of the discrepancy would be good for US I think. But it could just also be a warning that the init() value is being overridden by DVC. Up to you/@dberenbaum on this. Would you be reusing #74 @pared ?

**Comment by jorgeorpinel** [comment]
UX

**Comment by dberenbaum** [comment]
I don't feel strongly one way or the other TBH. @pared Do you have a preference?

**Comment by pared** [comment]
To be honest, after writing the change #74  and discussing potential scope of support (docs, warnings) required to make it work, it seems to me we should scrap this change.

1. It supports use case that is wrong from the project point of view (disrepancy between code and dvclive)
2. Is hard to comprehend, and has a potential to bring us some support tickets regarding the logic behind `init` 

I am all for keeping it around if users demand it, but for now I would close #74 and this issue.

**Comment by jorgeorpinel** [comment]
So what would be the correct workflow now? Don't configure it and let is use the default dir? (https://github.com/iterative/dvclive/pull/67)

**Comment by jorgeorpinel** [comment]
I'm guessing that even without `init()` in the code, we may still have a problem if the path sent to `stage add --live` doesn't match the default one. If so, at least we should consider my idea of not requiring an arg for `stage add --live`. I can close this issue and open one in the core DVC repo if you agree.

**Comment by pared** [comment]
> So what would be the correct workflow now? Don't configure it and let is use the default dir? (#67)

1. No `dvclive.init` and `--live` provided - use `--live` arg
2. `dvclive.init` and `--live` provided - if they don't match - throw

It seems I would have to modify #74 to handle 2nd use case.

> f so, at least we should consider my idea of not requiring an arg for stage add --live

Sorry, you are right, and I think this is a good idea. Just so that we are on same page:
`dvc run -n ... -d ... -o ... python code.py --live would mean that we produce `dvclive` dir?

**Comment by dberenbaum** [comment]
>     2\. `dvclive.init` and `--live` provided - if they don't match - throw
> 
> 
> It seems I would have to modify #74 to handle 2nd use case.

To confirm, does this throw an error now? If so, I think that's fine.

> `dvc run -n ... -d ... -o ... python code.py --live would mean that we produce `dvclive` dir?

+1 to this idea.

**Comment by pared** [comment]
@dberenbaum currently it will throw error, but due to fact that arg provided in `--live` does not exist, need to make it more informative.

**Comment by jorgeorpinel** [comment]
If it throws an informative error, then that's good enough.

If you'd like to make the `--live` arg optional on top of that, go for it! Up to you @pared 

(And yes, I'd expect no `--live` arg = default `dvclive/` report dir.)
