### ISSUE TITLE
dvcyaml: Prevent duplications

### ISSUE THREAD

**Issue by daavoo** [iterative/dvclive#604]
In order to prevent duplication (mainly `plots`), we could try to check if there is an existing `dvc.yaml` with overlapping information.

**Comment by daavoo** [comment]
@dberenbaum I don't recall if we discussed this already but makes sense to me to add a simple parsing check looking for overlaps with the root `dvc.yaml`.

**Comment by daavoo** [comment]
> What would you consider a duplicate? 

Literal duplicate. Path and props matching.

> It will be harder to explain and understand than the current behavior,

I feel like it is already hard today, not sure if the change would make it harder. 
At least it would prevent pitfalls, I doubt someone intentionally wants the duplication

**Comment by dberenbaum** [comment]
Okay, I'm also not sure whether it would be better or not, but no strong opinion from me if you want to try it.

**Comment by daavoo** [comment]
Closing in favor of #687
