### ISSUE TITLE
Proposal for more visual output options for standalone dvclive

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvclive#61]
Currently, dvclive without dvc produces just a tsv output tracking metrics progress. This doesn't seem like enough to make it worthwhile for users. There are at least a few drawbacks to the current output:
* It's not visual - some kind of plot, progress bar, etc. would be easier to read
* It's in a separate file that needs to be opened and refreshed as training progresses

Ideally, it would be great to have a nice dynamic plot that shows up in stdout during training and also optionally gets saved to a file at the end. More realistically, we might have different output options that users could choose or that dvclive could default to depending on what's available:
* Use dvc plots to visualize if installed (although this is still a static separate file)
* Use matplotlib or other python plotting libraries to render and update as training progresses
* Use stdout to make a very simplistic plot or to print out the metrics being written to tsv

Hopefully, there are better suggestions than these! Interested in thoughts on the general concept, and individual output types can be opened in separate issues if needed. Keeping dvclive as lightweight as possible should also remain a priority.

**Comment by pared** [comment]
related to https://github.com/iterative/dvc/discussions/5980

**Comment by daavoo** [comment]
Revisiting this. 

Now that we are moving towards depending on [dvc-render](https://github.com/iterative/dvc-render), I'm assuming it makes more sense to implement these different plotting options on `dvc-render` side, right?

> Use stdout to make a very simplistic plot or to print out the metrics being written to tsv

Would this be covered by #206 ?

**Comment by dberenbaum** [comment]
Once dvclive can generate plots without dvc, we can close this issue.
