### ISSUE TITLE
cache_images issues

### ISSUE THREAD

**Issue by CptCaptain** [iterative/dvclive#618]
I'm trying to use the new `cache_images` feature from the ultralytics repo, but I get this warning (though it feels more like an error):
```
WARNING:dvclive:Failed to dvc add dvclive/plots/images: 'PosixPath' object is not iterable
```
This causes the feature to fall apart, and no files are added to dvc.
To fix it, I've hacked a string-cast into the `live.py:cache` function. This solves the issue, but I'm not sure if that's the right way to do this.

**Comment by daavoo** [comment]
> To fix it, I've hacked a string-cast into the live.py:cache function. This solves the issue, but I'm not sure if that's the right way to do this.

Yes, this would be the easiest fix. Do you want to send a P.R?
