### ISSUE TITLE
`FileNotFoundError: [Errno 2] No such file or directory: 'dvclive/first_stage/params.yaml'` when using multiple nodes

### ISSUE THREAD

**Issue by hkenlay** [iterative/dvclive#624]
Hello Iterative. I use DVCLive in a multi-node setting and occasionally I get the following error

```
  File "myrepo/.venv/lib/python3.9/site-packages/dvclive/live.py", line 86, in __init__
    self._init_cleanup()
  File "myrepo/.venv/lib/python3.9/site-packages/dvclive/live.py", line 122, in _init_cleanup
    os.remove(f)
FileNotFoundError: [Errno 2] No such file or directory: 'dvclive/first_stage/params.yaml'
```

I think the issue may be that ones node reaches `os.remove(f)` and then the other node reaches this line before the first node finishes (therefore bypassing the `if f and os.path.exists(f):` check on line 121). 

I'm using PyTorch Lightning and Fabric and as a fix I put this in my training script 

```
from lightning.fabric import Fabric
from pathlib import Path
from dvclive import Live

if __name__ == '__main__':
    # initialise fabric and read params
    fabric = Fabric(devices=4, num_nodes=2)
    fabric.launch() 
    fabric.barrier() 
    if fabric.global_rank == 0:
        config = dvc.api.params_show()
    else:
        config = None
    params = fabric.broadcast(config, src=0)
    
    # remove files ahead of dvclive initialisation
    if fabric.global_rank == 0:
        files_to_delete = [
            Path('dvclive/first_stage/metrics.json'),
            Path('dvclive/first_stage/report.html'),
            Path('dvclive/first_stage/params.yaml'),
            Path('dvclive/first_stage/dvc.yaml')
        ]
        for file in files_to_delete:
            file.unlink(missing_ok=True)
    fabric.barrier()
      
    # rest of the script
    with Live(dir="dvclive/training") as live:
          pass
```

The final entry in `files_to_delete` was added to avoid the following similar error 

```
FileNotFoundError: [Errno 2] No such file or directory: 'dvclive/first_stage/dvc.yaml'
    self._init_cleanup()
  File "/myrepo/.venv/lib/python3.9/site-packages/dvclive/live.py", line 125, in _init_cleanup
    os.remove(self.dvc_file)
FileNotFoundError: [Errno 2] No such file or directory: 'dvclive/first_stage/dvc.yaml'
```

This solution is a bit unsatisfactory and bulky so as an alternative I removed the above lines under `#remove files ahead of dvclive initialisation`) and instead replaced lines 116-125 of `src/dvclive/live.py` (below)

```
        for f in (
            self.metrics_file,
            self.report_file,
            self.params_file,
        ):
            if f and os.path.exists(f):
                os.remove(f)

        if self.dvc_file and os.path.exists(self.dvc_file):
            os.remove(self.dvc_file)
```

with

```
        for f in (
            Path(self.metrics_file),
            Path(self.report_file),
            Path(self.params_file),
        ):
            f.unlink(missing_ok =True)

        Path(self.dvc_file).unlink(missing_ok=True)
```

By trying to remove and checking for the file existence in a single line the issue seems to have resolved. Is this something I could make into a PR?

---
Additional information:
OS: Ubuntu 20.04
Python version: 3.9.16
DVCLive version: 2.12.1
DVC version: 3.5.1

**Comment by daavoo** [comment]
Hi @hkenlay , the fix you mention works as a way to solve the symptom, but I would like to better understand the use case and root cause better.

I think what we might need to do is provide a logger compatible with fabric (https://lightning.ai/docs/fabric/stable/api/loggers.html).

Is there a use case where you need to manually create a `Live` instance? Do you need to share the instance across nodes?

**Comment by hkenlay** [comment]
Hello @daavoo. I'm using PyTorch Lightning to train a model across multiple nodes. 

The job is submitted via slurm and in my slurm submission script I use
```
dvc exp run -S base.cmd="srun python"
dvc exp push origin --rev HEAD
```
to start the experiment and push the results. To the best of my knowledge these commands are just run on the first node. My `params.yaml` file has 
```
base:
  cmd: python
```
and `dvc.yaml` starts
```
stages:
  train:
    cmd: ${base.cmd} scripts/train.py
```
which allows me to have a normal `python script/train.py` by default but I can do `srun python script/train.py` for multinode training (as per https://lightning.ai/docs/pytorch/stable/clouds/cluster_advanced.html). Because `dvc exp run` is only run on the first node, I use Fabric to pass across the `params.yaml` file to the second node via fabric (I use Fabric because its a bit easier to use compared to something like MPI, and I'm already using PyTorch Lightning which I believe uses Fabric under the hood). 

I use `with Live(dir="dvclive/training") as live:` so I can pass the `live` instance to a `DVCLiveLogger` as per this example `https://dvc.org/doc/dvclive/ml-frameworks/pytorch-lightning#examples`. I'm not sure how this object handles sharing the `live` instance across nodes, but I have no problem writing checkpoints and logs in this scenario, I'm guessing the underlying PyTorch Lightning Logger takes care of this.  

I think another solution to this problem is to only create and use a live instance on the first node, but this might generate a lot of boilerplate code.

**Comment by hkenlay** [comment]
Taking a closer look. If I don't specify a `Live` object and let the `DVCLiveLogger` handle creating it, this would happen on the first node as it would be created by 
```
@property  # type: ignore
@rank_zero_experiment
def experiment(self):
```

Instead of passing a `live` instance to `DVCLiveLogger`, I can just pass `dir='dvclive/training`?

**Comment by daavoo** [comment]
> Instead of passing a live instance to DVCLiveLogger, I can just pass dir='dvclive/training?

If modifying `dir` is the only thing you are doing with the `Live` instance outside of the logger, yes

**Comment by hkenlay** [comment]
Worked a charm, thanks @daavoo
