### ISSUE TITLE
ModuleNotFoundError: No module named 'lightning'

### ISSUE THREAD

**Issue by aschuh-hf** [iterative/dvclive#625]
I installed `dvclive=2.12` from `conda-forge` using `mamba`. I have `pytorch_lightning=2.0.4` installed, but not `lightning`. The installation of DVC did not require it either, and the missing import would also be available through `lightning_fabric.utilities.logger` instead of `lightning.fabric.utilities.logger`.

```
    from dvclive.lightning import DVCLiveLogger
  File "/opt/conda/envs/venv/lib/python3.10/site-packages/dvclive/lightning.py", line 5, in <module>
    from lightning.fabric.utilities.logger import (
ModuleNotFoundError: No module named 'lightning'
```

**Comment by aschuh-hf** [comment]
I see that with `pip`, I would have needed to specify extra `lightning` (https://github.com/iterative/dvclive/blob/28a022422c47b885e074b0d13e0adeee77bd545b/pyproject.toml#L65).

But I wonder if it would be possible to modify DVCLive that it suffices to have `pytorch-lightning` installed rather than the more recent `lightning` package? Ray Train 2.5 still uses `pytorch-lightning`.

**Comment by daavoo** [comment]
> But I wonder if it would be possible to modify DVCLive that it suffices to have pytorch-lightning installed rather than the more recent lightning package

Yes, I think we could add some try/excepts on the imports to make it compatible with both packages.

Sorry for the inconvenience, I didn't pay much attention to how/when they decided to migrate and change package names (couldn't find any guide for libraries depending on that) and thought that imports would be somehow compatible after upgrading to the `lightning` name.

We are aiming to contribute and move the loggers to the ML framework repositories to avoid this kind of things

**Comment by aschuh-hf** [comment]
#627 May need a minor adjustment. The following import differs between `lightning` and `pytorch_lightning`.

New `lightning` import:
```
from lightning.pytorch.loggers.utilities import _scan_checkpoints
```

Current alternative import after #627 which raises a `ModuleNotFoundError`:
```
from pytorch_lightning.utilities.logger import _scan_checkpoints
```

Required fix of `dvclive/lightning.py` import statement to make it work:
```
from pytorch_lightning.loggers.utilities import _scan_checkpoints
```
