### ISSUE TITLE
HuggingFace: Add `log_model`

### ISSUE THREAD

**Issue by daavoo** [iterative/dvclive#641]
Similar to https://github.com/iterative/dvclive/pull/640

**Comment by dberenbaum** [comment]
For the record, here's how it's handled in other loggers (see https://huggingface.co/docs/transformers/v4.31.0/en/main_classes/callback):

Wandb:

> WANDB_LOG_MODEL (str, optional, defaults to "false"): Whether to log model and checkpoints during training. Can be "end", "checkpoint" or "false". If set to "end", the model will be uploaded at the end of training. If set to "checkpoint", the checkpoint will be uploaded every args.save_steps . If set to "false", the model will not be uploaded. Use along with load_best_model_at_end() to upload best model.

Mlflow:

> HF_MLFLOW_LOG_ARTIFACTS (str, optional): Whether to use MLflow .log_artifact() facility to log artifacts. This only makes sense if logging to a remote server, e.g. s3 or GCS. If set to True or 1, will copy each saved checkpoint on each save in [TrainingArguments](https://huggingface.co/docs/transformers/v4.31.0/en/main_classes/trainer#transformers.TrainingArguments)’s output_dir to the local or remote artifact storage. Using it without a remote storage will just copy the files to your artifact location.

Neptune:

> log_checkpoints (str, optional) — If “same”, uploads checkpoints whenever they are saved by the Trainer. If “last”, uploads only the most recently saved checkpoint. If “best”, uploads the best checkpoint (among the ones saved by the Trainer). If None, does not upload checkpoints.
