### ISSUE TITLE
Transition to pipelines

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvclive#648]
Issues with transitioning to pipelines:
1. Not clear what to track as output 
2. Tracking the [entire output folder](https://github.com/iterative/dvclive/issues/456) causes problems with the dvclive dvc.yaml
3. May want to move params from outputs to deps and drop some/all dvclive params to avoid duplication
4. Anything cached by dvclive (for example, using `log_artifact`) needs to be moved to a stage output and removed as a standalone .dvc file
5. DVCLive writes dvc.yaml to subdir but pipeline should be at root

Some ideas for how to help with the transition to pipelines (none are new, but trying to consolidate them here):

1. [Reintroduce](https://github.com/iterative/dvclive/pull/497) printing out a stage template or write one to a file (`dvclive/stage_template.yaml`).
6. Add a top-level `outs` section in `dvclive/dvc.yaml` and a corresponding `dvclive/dvc.lock` file so all outputs are captured within the `dvclive` dir and can be easily dropped/moved to a stage in the top-level `dvc.yaml` (and outputs get dropped each time so you don't have stale outputs).
7. [CLI entry point](https://github.com/iterative/dvclive/issues/648#issuecomment-1665219052) to do an automated, opinionated migration (i..e dvclive.pipeline_migration or something)?
8. When dvc stage add overlaps with an existing output, it can prompt to do dvc remove automatically instead of fail.

**Comment by shcheklein** [comment]
Thanks, @dberenbaum ! Can we also summarize the requirements / issues that we see now in this ticket (can be "as we go" / from the top of your head). From what I remember - params (becomes duplicated and needed to actually run an experiment), loggers (like YOLO - would need additional way to configure it / recognize the pipeline and don't dump certain things for example).

**Comment by daavoo** [comment]
> Some ideas for how to help with the transition to pipelines (none are new, but trying to consolidate them here):

Why don't we introduce an explicit CLI entry point to do all those things (i..e `dvclive.make_pipeline`)?

**Comment by dberenbaum** [comment]
> loggers (like YOLO - would need additional way to configure it / recognize the pipeline and don't dump certain things for example)

Can you clarify? Trying to understand how much is specific to yolo vs general issues with loggers

**Comment by dberenbaum** [comment]
> Why don't we introduce an explicit (call it when you need) CLI entry point to do an automated, opinionated migration (i..e `dvclive.pipeline_migration` or something)?

Added to the list. Do you have an idea of how to make it work? Maybe we need to combine it with the idea of writing out the stage template each time so we know what to do during migration? I guess I'm unclear on how we collect the stage info if we invoke it any time other than `live.end()` (since that's when we would have the full dvclive context).

**Comment by daavoo** [comment]
>  I guess I'm unclear on how we collect the stage info if we invoke it any time other than live.end() (since that's when we would have the full dvclive context).

I was thinking of something you call completely outside the training code (a separate CLI call you make when you want to transition), and assume you have a `dvclive` folder of a completed experiment.
So, we parse the output folder and assume that is the context

**Comment by dberenbaum** [comment]
Okay, I guess that depends on us having some record of every `.dvc` file added (which we can do but isn't true today) and having a way to reverse engineer everything. What would be the advantages over writing some extra file at the end of training that would already have all that info?

**Comment by shcheklein** [comment]
> Can you clarify? Trying to understand how much is specific to yolo vs general issues with loggers

E.g. I have a model as an output and I have it logged in a logger. I would need a way to disable the logger behavior in some way. In case of YOLO it becomes even more problematic since it's integrated deep into the framework itself.

Params - I think it's clear. We don't want them to be duplicated. Thus we need a way to disable this.

Plots / metrics - can it be that some of them will migrate to `dvc.yaml`? Is there a reason for this?

**Comment by dberenbaum** [comment]
Some discussions where this confused users:
* https://discord.com/channels/485586884165107732/485596304961962003/1138460354318446622
* https://iterativeai.slack.com/archives/CB41NAL8H/p1691588244681379

**Comment by dberenbaum** [comment]
One more small idea here: when `dvc stage add` overlaps with an existing output, it can prompt to do `dvc remove` automatically instead of fail.

**Comment by dberenbaum** [comment]
Here's a high-level proposal since it seems we are getting a bit lost in details:

When you start running dvclive without a dvc pipeline, everything that dvclive tracks should be within the dvclive dir, so you will end up with a dir like:

```
dvclive
├── dvc.lock # proposed new file with hash info for files from `Live.log_artifact()`
├── dvc.yaml
├── dvc_stage_template.yaml # proposed new file to write info needed for stage transition
├── metrics.json
├── params.yaml
├── plots
...
└── report.html
```

This makes it easy to see and manage everything dvclive does, drop anything related to dvclive, and transition all dvclive info to pipelines. When ready to transition to pipelines, if you have no root `dvc.yaml` yet, you can do `cp dvclive/dvc_stage_template.yaml dvc.yaml`. If you already have a root `dvc.yaml`, you can copy the contents into there. Once you are finished, you can `rm -r dvclive` and run as a pipeline. We can also make some CLI helper to do this.

You should not have to touch your dvclive code. `log_artifact()` calls should auto-detect if you are running a pipeline. `log_params` and similar calls should likewise check if there are duplicates already defined in the stage that is running and will skip them as needed. For example:

```python
with Live(save_dvc_exp=True) as live:
    live.log_param("epochs", EPOCHS) # if the stage already has a param `epochs`, dvclive could skip it

    for i in range(EPOCHS):
        live.log_metric("metric", i + random.random())
        live.log_image(f"img/{live.step}.png", img) # will skip caching if already enabled by the stage (or warn otherwise)
        live.next_step()

    live.log_artifact("model.pt", type="model", name="mymodel") # will skip caching if already enabled by the stage
```

**Comment by daavoo** [comment]
Maybe just staying the obvious here but IMO the most important thing to address, regardless of the implementation, is to clearly explain and separate in the docs:

- Running DVCLive _without_ a DVC Pipeline
- Running DVCLive _with_ a DVC Pipeline
- How to transition from _without_ to _with_

Even if the transition today involves many manual steps, the problem is that is not clear in the docs the scenario assumed in a page (this is especially missing in the DVCLive API pages).

**Comment by dberenbaum** [comment]
> dvc_stage_template.yaml # proposed new file to write info needed for stage transition

Let's start here since it's simple and provides significant value. It can look similar to https://github.com/iterative/dvclive/pull/497 but written to a file instead of to logs so it's less noisy and persisted to a file for use any time.

**Comment by dberenbaum** [comment]
As @daavoo suggested, I wonder if https://github.com/iterative/dvc.org/pull/4788 is enough to lower the priority here. It would be nice to also have a helper for transitioning to pipelines, but I'm still torn on the best approach here. Some of the options:

1. #679: I worry that asking users to manually modify `dvc.yaml` files is too low-level and still leaves them to manage friction like having to call `dvc remove`. 
2. CLI helper: might be smoother and be able to handle all the commands needed, but I worry that it could quickly turn into too much magic like `dvc exp init`, and DVCLive would still need to write out what the stage should look like (we could try to parse this from the contents of the DVCLive directory, but I think it's too brittle).
3. Write out the set of commands to a file: We could write that into the report file or some other file to run when the user is ready. Something like:

```
dvc remove data.xml dvclive/artifacts/model.pkl dvclive/images
dvc stage add -d <script.py> -o data.xml -o dvclive/artifacts/model.pkl -o dvclive/images <python script.py>
```

Thoughts?

**Comment by mnrozhkov** [comment]
> dvc remove data.xml dvclive/artifacts/model.pkl dvclive/images
> dvc stage add -d <script.py> -o data.xml -o dvclive/artifacts/model.pkl -o dvclive/images <python script.py>

This approach looks like a good workaround. There are a couple of things to clarify: Does it mean, that users may keep DVCLive loggers in the code, and their behavior will not change? E.g. DVCLive will not create `.dvc` files for the logged artifacts

**Comment by dberenbaum** [comment]
> Does it mean, that users may keep DVCLive loggers in the code, and their behavior will not change? E.g. DVCLive will not create `.dvc` files for the logged artifacts

Sorry for the delayed response. Yes, in fact `Live.log_artifact()` already works like this when you run a pipeline.
