### ISSUE TITLE
warn on `repro` usage

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvclive#670]
Saving the experiment and other features of dvclive won't work when using `repro` instead of `exp run`. We need to detect when `repro` is being used and warn the users to do `exp run` instead.

**Comment by omesser** [comment]
@dberenbaum @daavoo  - 2 questions:
- warn vs fail - Do we want to warn just to not break existing user workflows - should we state that in the future (next major release) this will be a failure and not supported? are there any downside of asking users to do `exp run` ?
- verifying I'm not missing anything - `dvc repro` is problematic, `dvc exp run` isn't, and running with just Python (directly, via shebang, or some wrapper like [pdm](https://pdm.fming.dev/latest/)) is safe? obvious example: `python script.py`

**Comment by dberenbaum** [comment]
> * warn vs fail - Do we want to warn just to not break existing user workflows - should we state that in the future (next major release) this will be a failure and not supported? are there any downside of asking users to do `exp run` ?

We err on the side of warning over failing in dvclive because the logger is often a pretty minor part of an often expensive, long-running training job, and it can be frustrating to have it break (possibly after hours) because of an error with your logger setup.

> * verifying I'm not missing anything - `dvc repro` is problematic, `dvc exp run` isn't, and running with just Python (directly, via shebang, or some wrapper like [pdm](https://pdm.fming.dev/latest/)) is safe? obvious example: `python script.py`

Correct. With `dvc exp run`, DVC already takes care of saving the experiment and DVCLive can skip these operations. With Python only, DVCLive can save the experiment itself. With `dvc repro`, DVC is already running but not saving the experiment, and we have no way to intervene in the existing DVC process to save it.

**Comment by omesser** [comment]
Got it, thanks for the clarifications @dberenbaum !
