### ISSUE TITLE
Failed to post to Studio

### ISSUE THREAD

**Issue by theoh-io** [iterative/dvclive#675]
I have a setup with DVC and Ultralytics Yolov8 where I can successfully log my training metrics with dvc live to studio. However on the other machine (Jetson Orin) with the same setup (matching dependency versions) I get the following Warnings:

At the beginning of training:
WARNING:dvclive:'dvclive/dvc.yaml' is in outputs of stage 'dvclive.dvc'.
Remove it from outputs to make DVCLive work as expected.

content of dvclive.dvc:
outs:
- md5: 389513330920738ff1370ef5fef7b90b.dir
  nfiles: 36
  hash: md5
  path: dvclive
  size: 104109217

at each training epoch:
WARNING:dvc_studio_client.post_live_metrics:Failed to post to Studio: Out of range float values are not JSON compliant
WARNING:dvclive:`post_to_studio` `data` event failed. Data will be resent on next call.

I just instqlled dvclive and setup dvc logging true in Yolo settings.

**Comment by theoh-io** [comment]
@daavoo  Thanks for the fast response !

here is my pipeline:
stages:
  train:
    cmd: python train.py
    params:
    - train
    deps:
    - train.py
    - data
  test_inference:
    cmd: python track.py
    deps:
    - inference
    - model.pt
    - track.py

artifacts:
  yolo-model:
    path: model.pt
    type: model
    desc: 'Object Detection model, Yolov8'
    labels:
      - object detection

Yes dvclive is being tracked by dvc.

It seems strange to me that it run smoothly on my first machine. I verified the versions of dvc (3.12) and dvclive (2.14) and they match.

I will check the outcome of the open issue thanks for the support :)

**Comment by daavoo** [comment]
> Yes dvclive is being tracked by dvc.

Unfortunately, the `dvclive/dvc.yaml` file is not meant to be cached by DVC.

Is there a reason for you to `dvc add` the entire `dvclive` folder?

If you still want to track all dvclive contents with DVC, you would need to skip `dvclive/dvc.yaml`.

One option would be to `dvc remove dvclive.dvc` and track the rest of the contents individually (i.e. `dvc add dvclive/plots`).

Note that DVCLive has the option to automatically track the images with DVC if you pass `Live(cache_images=True)`, the rest of the contest are plain text files which should not be a problem to track with Git

**Comment by theoh-io** [comment]
@daavoo thanks for your help !

Actually Im using dvclive automatic logging with Yolov8 as described here: https://dvc.org/doc/dvclive/ml-frameworks/yolo. I would also be interested in knowing how I can customize or add other metrics in the logging.

Concerning the file tracked by dvc I thought it would be useful to compare the metrics for the different experiment I am running. But maybe Im wrong here, do we only want to track large file with DVC and the rest with git ?

**Comment by daavoo** [comment]
Closing since the Studio bug has been fixed and (hopefully) the expectations of what to track with git and what with DVC have been clarified
