### ISSUE TITLE
lightning: Do not convert lists to strings in log_hyperparams()

### ISSUE THREAD

**Issue by aschuh-hf** [iterative/dvclive#680]
`dvclive.lightning.DVCLiveLogger` uses the private [_sanitize_params()](https://github.com/Lightning-AI/lightning/blob/6df43685ee2f2dd0c53eefec295e0d6c79796fd2/src/lightning/fabric/utilities/logger.py#L100-L128) helper of PyTorch Lightning (Fabric) to convert non-primitive types to strings for logging. However, this includes lists. Given that the parameters are in case of DVC logged to a YAML file which supports lists, it may be better to preserve those lists.

I also have a tuple `input_size` with value `(256, 256, 256)` in the `params` dict I pass to `self.save_hyperparameters()` which gets converted to a string. A list would seem more appropriate for sequence types. However, I could also convert it explicitly to a list before passing it to `self.save_hyperparameters()` in my `LightningModule`. But the lists should not be converted to strings.

For example this `params.yaml` produced by `DVCLiveLogger`:
```
num_features: '[32, 32, 16, 16, 8]'
optimizer_betas: '[0.9, 0.999]'
input_size: (256, 256, 256)
```
should be
```
num_features: [32, 32, 16, 16, 8]
optimizer_betas: [0.9, 0.999]
input_size: [256, 256, 256]
```

**Comment by aschuh-hf** [comment]
The only use of `_sanitize_params()` I found in the PyTorch Lightning GitHub repository is in the implementation of the TensorBoardLogger. But it may well be that TensorBoard doesn't support list values, but YAML does.

https://github.com/search?q=repo%3ALightning-AI/lightning%20_sanitize_params&type=code

**Comment by aschuh-hf** [comment]
This version of `_sanitize_params()` added to the module defining my patched `DVCLiveLogger` subclass solves this.

```
def _sanitize_params(params: Dict[str, Any]) -> Dict[str, Any]:
    """Returns params with types not supported by YAML to strings."""
    for k in params:
        # convert relevant np scalars to python types first (instead of str)
        if isinstance(params[k], (np.bool_, np.integer, np.floating)):
            params[k] = params[k].item()
        elif isinstance(params[k], tuple):
            params[k] = list(params[k])
        elif type(params[k]) not in (bool, int, float, str, list, Tensor):
            params[k] = str(params[k])
    return params
```

It's based on the respective function from Fabric. Note that I included conversion from `tuple` to `list` here.

**Comment by dberenbaum** [comment]
I think we could drop `_sanitize_params()` and follow other loggers like in https://github.com/Lightning-AI/lightning/blob/2ca157106518c1b3b357df34f9541f588f22475e/src/lightning/pytorch/loggers/wandb.py#L413-L417.
