### ISSUE TITLE
YoloV8 Integration 

### ISSUE THREAD

**Issue by BradyJ27** [iterative/dvclive#714]
The yolov8/dvclive compatibility is not working as expected. The results of the demo colab [notebook](https://colab.research.google.com/github/iterative/dvclive/blob/main/examples/DVCLive-YOLO.ipynb) are not showing as expected. It looks like Yolo isn't even picking up that DVCLive is installed at all. Opening here just to make aware, I can also open an issue in Ultralytics if needed.

**Comment by shcheklein** [comment]
@BradyJ27 for the record - https://github.com/ultralytics/ultralytics/pull/4894/files#r1333816643 . I'm looking into this, but I need some context from the maintainers first. (cc @@glenn-jocher for visibility)

**Comment by BradyJ27** [comment]
> @BradyJ27 for the record - https://github.com/ultralytics/ultralytics/pull/4894/files#r1333816643 . I'm looking into this, but I need some context from the maintainers first. (cc @@glenn-jocher for visibility)

Got it, thanks! Just wanted to make sure this was on the radar somewhere!

**Comment by shcheklein** [comment]
yep, thanks a lot for creating the issue for this!

**Comment by BradyJ27** [comment]
Fixed in https://github.com/ultralytics/ultralytics/issues/5058 ultralytics==8.0.186 

For others that may have been affected, try updating ultralytics >= 8.0.186
