### ISSUE TITLE
`xgboost`: clarify docs: make it easier to add metrics to an existing project

### ISSUE THREAD

**Issue by djsauble** [iterative/dvclive#721]
I went through the process of instrumenting an XGBoost model with DVCLive, following [our docs](https://dvc.org/doc/dvclive/ml-frameworks/xgboost).

Where I got stuck was figuring out how to add additional metrics. The default metric was RMSE, but I'm not sure how this was chosen or how to swap in a different metric (e.g. accuracy or ROC AUC).

Is it possible to add a button somewhere that makes it easier to do this?

**Comment by dberenbaum** [comment]
Thanks for trying this out @djsauble! Improving the framework integrations and docs around them is exactly what we need in dvclive, so if you have time and want to help out, it's much appreciated. Xgboost hasn't been updated in a long time and would be a useful framework to update.

Regarding parameters, there's unfortunately not support for them for xgboost yet (see https://github.com/iterative/dvclive/issues/317), although it's another top priority. 

Regarding metrics, a more end-to-end example and link to the relevant xgboost docs (although it's unfortunate I don't see any direct hyperlink to `eval_metric` in their docs) would be really helpful to add to the docs. There is a decent example in the comet docs: https://www.comet.com/docs/v2/integrations/ml-frameworks/xgboost/#end-to-end-example.

**Comment by djsauble** [comment]
https://github.com/iterative/dvc.org/pull/4917
