### ISSUE TITLE
integrations: hf accelerate

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvclive#731]
DVCLive already supports `transformers`, but we should add support for [accelerate](https://github.com/huggingface/accelerate/blob/main/src/accelerate/tracking.py).

**Comment by dberenbaum** [comment]
Started on #732, but in distributed jobs, AFAICT there is a bug with custom/external trackers. Rather than try to go deeper into it, I think it's better to finally make the move to migrate these callbacks to their respective ML frameworks.

**Comment by dberenbaum** [comment]
Related to #221

**Comment by dberenbaum** [comment]
Completed in https://github.com/huggingface/accelerate/pull/2139

**Comment by shcheklein** [comment]
Amazing, @dberenbaum ! good stuff.
