### ISSUE TITLE
Log metrics/models etc... to studio directly with Live or DVCLiveCallbacks in training script

### ISSUE THREAD

**Issue by BaptisteLoquette** [iterative/dvclive#734]
Hello, I was wondering if there is a way to directly log params, metrics, etc... to iterative ai studio within the training script using Live or DVCLiveCallbacks (hugging face) instances. If not, I don't really get how to do this tbh. is this through dvc exp push ?
Thanks a lot in advance.
Great work from all the iterative ai team btw !!

**Comment by BaptisteLoquette** [comment]
Hello, I was wondering if there is a way to directly log params, metrics, etc... to iterative ai studio within the training script using Live or DVCLiveCallbacks (hugging face) instances. If not, I don't really get how to do this tbh. is this through dvc exp push ?
Thanks a lot in advance.
Great work from all the iterative ai team btw !!

**Comment by dberenbaum** [comment]
Yes @BaptisteLoquette, you need to include a Studio token locally to see them live in Studio. See https://dvc.org/doc/studio/user-guide/experiments/live-metrics-and-plots#set-up-an-access-token. We can better clarify this in the DVCLive docs.

Can you better describe how you got to this point? Were you already using DVC or started with DVCLive? Where did you go in the docs to try to find this info?

**Comment by BaptisteLoquette** [comment]
I already used dvc & cml. But new to the studio. I already added the studio token in the gitlab variables. And at each git trigger (here push) the commit appears on the studio though, except for the data size, nor the metrics, loss are models are logged/registered. I do think it's because I haven't configured a dvc.yaml file in my current project. Also, I configured an azure blob storage. When I log_artifact the model, it will be stored in the blob storage right ?

Thx for your answer

**Comment by BaptisteLoquette** [comment]
I mean it's logical that the data size is logged as I dvc pushed the datas, but I was thinking Using Live() or DVCLiveCallback would automatically log the metrics etc... to the studio

**Comment by BaptisteLoquette** [comment]
Huh, no sry didn't see this https://dvc.org/doc/user-guide/project-structure/configuration#studio I need to enable it in the config right ?

**Comment by dberenbaum** [comment]
> I mean it's logical that the data size is logged as I dvc pushed the datas, but I was thinking Using Live() or DVCLiveCallback would automatically log the metrics etc... to the studio. Only from the training script and no git action.

Yes, that's how it should look. It sounds like something isn't configured right for you.

> Huh, no sry didn't see this https://dvc.org/doc/user-guide/project-structure/configuration#studio I need to enable it in the config right ?

> I already added the studio token in the gitlab variables.

The token needs to be either in your dvc config under `studio.token` or in the environment variable `DVC_STUDIO_TOKEN`.

**Comment by BaptisteLoquette** [comment]
Fixed it, by setting with dvc config --global studio.token. But weird because it starts inside a gitlab CI script and DCC STUDIO TOKEN was configured in the variables

**Comment by BaptisteLoquette** [comment]
Thx a lot for your answers

**Comment by dberenbaum** [comment]
If you want to post your CI script, we can try to debug. If not, I guess we can close the issue?

**Comment by BaptisteLoquette** [comment]
It's fixed. yes we can. Thx a lot again
