### ISSUE TITLE
Feature Request: Support different formats of summaries

### ISSUE THREAD

**Issue by Benjamin-Etheredge** [iterative/dvclive#75]
Summaries are currently printed out as a single JSON line. It would be handy to be able to change this format to a more readable format (such as YAML or multiline JSON).
These summaries are more likely to be checked into git. As such, having them in a more human-readable format would be beneficial.

**Comment by pared** [comment]
While the issue itself seems easy to implement, it unravels new problem that we had to address at some point: dvclive configuration.

**Comment by dberenbaum** [comment]
Can we start with the easy implementation 😆 ?

**Comment by pared** [comment]
@dberenbaum yes we can, we can probably pass it silently by replacing `summary` flag with string arg `summary_path` that will also tell dvc what format we want the summary in. Though in that case there would be some reworking needed also on DVC side.

**Comment by dberenbaum** [comment]
I was thinking even smaller, like can we just dump the json with an indent value so that it gets pretty printed?

**Comment by pared** [comment]
Ahh, ok, I guess my imagination went too far. Give me a sec...

**Comment by pared** [comment]
@Benjamin-Etheredge would properly formatted json be good enough for start? Created PR for that.

**Comment by pared** [comment]
Fixed in #78. We can revisit it if we need yaml support, though purely aesthetics reasoning is not enough to justify amount of changes needed to support different summary formats. (It would require configuration, which is currently not necessary for `dvclive`)
