### ISSUE TITLE
DVCLive throws a weird warning when origin is not defined

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvclive#753]
If repo is new and there is no origin yet. Most likely needs to be reviews on the Studio side. 

`{"detail":"Permission denied or repo not found, check that origin is a self-hosted gitlab repo"}`

**Comment by dberenbaum** [comment]
What do you think should happen in this case? Can you provide more of the context of the output outside of this line?

**Comment by shcheklein** [comment]
Just a less confusing message (e.g. not mention GitLab self-hosted). We don't need any major changes here.

**Comment by shcheklein** [comment]
Context- it was a new repo, I did git init locally and ran your notebook from fabric example in it AFAIR.

**Comment by shcheklein** [comment]
I don't anymore, but it's a regular framework output I believe - not much about dvclive. I can run it again if you feel it is needed.

**Comment by dberenbaum** [comment]
No, I can reproduce it, thanks. My initial thought is that it's a dvc-studio-client issue. We shouldn't be sending anything to studio if we can't figure out a valid git remote name/url to send.
