### ISSUE TITLE
logging: configure logs directory

### ISSUE THREAD

**Issue by Benjamin-Etheredge** [iterative/dvclive#76]
The ability to control the logging directory in `dvc.yaml` files is excellent. However, it does not appear to support subdirectories. Logs must be in the current running directory. It would be helpful to be able to specify a directory to place generated logs into as a configuration option under the `live` tag in `dvc.yaml`

**Comment by Benjamin-Etheredge** [comment]
I'm not sure if this request should go under dvclive or DVC. Let me know if it should be moved to DVC.

**Comment by pared** [comment]
related: #77 , #75

**Comment by pared** [comment]
@Benjamin-Etheredge I have tried reproducing the problem with following script:
```bash
#!/bin/bash

set -ex

rm -rf test_workspace
mkdir test_workspace
pushd test_workspace

mkdir test_repo
pushd test_repo

git init --quiet
dvc init --quiet

git add -A
git commit -am "initial"

echo -e "
import dvclive

for i in range(10):
	dvclive.log('val', i)

" >> code.py

git add -A
git commit -am "add code"

dvc run -n train -d code.py --live sub/another_sub/logs python code.py
```

and dvclive succesfully creates `sub/another_sub/logs`  which seemed to be original problem here.
I checked the script for current master, `0.0.1`, `0.0.2` and `0.0.3` - all pass. Did I misunderstood the issue?

**Comment by daavoo** [comment]
Closing as stale. Feel free to reopen
