### ISSUE TITLE
logger: env var configuration

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvclive#79]
> Detected in https://github.com/iterative/dvclive/pull/74#pullrequestreview-662763978

Apparently DVCLive can be configured via env vars 🙂 

https://github.com/iterative/dvclive/blob/657fbfada181a8f0485779f376afb21f80986797/dvclive/metrics.py#L51-L68

I don't see this info neither in the [README](https://github.com/iterative/dvclive/blob/master/README.rst) nor in any page of https://dvc.org/doc/dvclive. Should we add it?

> Esp. if #74 gets merged.

**Comment by pared** [comment]
@jorgeorpinel env variables is means of passing configuration from `dvc` to `dvclive`. The main point of that is to be able to control pass `--live` and friends options. So I wouldn't document it, to not encourage anyone to use it.

**Comment by jorgeorpinel** [comment]
OK I was unaware of this mechanism. It's an implementation detail then (no docs required)... Unless there's a use case for setting this manually? Not in the context of `dvc`. Cc @dberenbaum WDYT?

**Comment by jorgeorpinel** [comment]
Another Q though. Was there a reason to pick env vars over some other "more internal" mechanism? E.g. similar to dvc checkpoints that use a signal file somewhere in .dvc/tmp

**Comment by dberenbaum** [comment]
> OK I was unaware of this mechanism. It's an implementation detail then (no docs required although an expandable section wouldn't hurt either)... Unless there's a use case for setting this manually? Outside the context of `dvc`. Cc @dberenbaum WDYT?

If it's only intended for internal usage, I don't think it needs to be documented.

**Comment by pared** [comment]
Closing for now, as its implementation detail. If we will get requests to document that, we can reopen.
