### ISSUE TITLE
integrations: HuggingFace transformers

### ISSUE THREAD

**Issue by daavoo** [iterative/dvclive#83]
It would be nice to have a `dvclive` integration with the popular repository [transformers](https://github.com/huggingface/transformers/) from huggingface.

Existing integrations are maintained in the repository implemented as callbacks:

https://github.com/huggingface/transformers/blob/master/src/transformers/integrations.py
https://huggingface.co/transformers/main_classes/callback.html#available-callbacks

We would maintain the implementation in the DVCLive repository.

- [ ] Add new callback to DVCLive
- [x] Update docs in [dvc.org](https://github.com/iterative/dvc.org)

**Comment by pacifikus** [comment]
@daavoo Should we only save the train metrics, or do we need valid metrics as well?

**Comment by daavoo** [comment]
> @daavoo Should we only save the train metrics, or do we need valid metrics as well?

For consistency I think we should also save validation metrics. Does this affect the inplementation details?

**Comment by pacifikus** [comment]
> > @daavoo Should we only save the train metrics, or do we need valid metrics as well?
> 
> For consistency I think we should also save validation metrics. Does this affect the inplementation details?

After some research, it seems to me that we can get the eval metrics from the log or callback, but not the training metrics. One way to deal with this is to use a manual call to the evaluation function on the train set, but this will slow down the training process.

https://discuss.huggingface.co/t/trainer-api-to-log-both-training-and-validation-metrics/7785

https://discuss.huggingface.co/t/metrics-for-training-set-in-trainer/2461

How about saving only the eval metrics?

**Comment by daavoo** [comment]
> After some research, it seems to me that we can get the eval metrics from the log or callback, but not the training metrics. One way to deal with this is to use a manual call to the evaluation function on the train set, but this will slow down the training process.
> 
> https://discuss.huggingface.co/t/trainer-api-to-log-both-training-and-validation-metrics/7785
> 
> https://discuss.huggingface.co/t/metrics-for-training-set-in-trainer/2461
> 
> How about saving only the eval metrics?

Great research!. I guess that saving only the eval metrics makes sense, as it will be consistent with how other ML Loggers work with HuggingFace.
