### ISSUE TITLE
integrations: pytorch lightning

### ISSUE THREAD

**Issue by daavoo** [iterative/dvclive#85]
It would be nice to have a `dvclive` integration with the popular training framework [PyTorch Lightning](https://www.pytorchlightning.ai/)

Existing integrations are maintained in the repository implemented as callbacks:

https://github.com/PyTorchLightning/pytorch-lightning/tree/master/pytorch_lightning/loggers
https://pytorch-lightning.readthedocs.io/en/1.2.9_a/common/loggers.html

We would maintain the implementation in the DVCLive repository.

- [ ] Add new callback to DVCLive
- [ ] Update docs in [dvc.org](https://github.com/iterative/dvc.org)

**Comment by pared** [comment]
Sample logger implementation can be found under [one of pytorch discussions](https://github.com/PyTorchLightning/pytorch-lightning/issues/1882)
