### ISSUE TITLE
logger: Add notifier to `next_step`?

### ISSUE THREAD

**Issue by daavoo** [iterative/dvclive#90]
Depending on the type of model to be trained, the time in between calls to `next_step`  may vary significantly. In common deep learning scenarios, i.e. the [keras callback](https://github.com/iterative/dvclive/blob/master/dvclive/keras.py), `next_step`  is being called at the end of an epoch which could result in long times (maybe hours) in between calls.

It could be useful to have built-in support for optionally sending a notification each time `next_step` is being called. 

Without changing `dvclive`, the user could just call a custom library (i.e. https://github.com/liiight/notifiers) after next_step:

```python
class MetricsCallback(Callback):
    def on_epoch_end(self, epoch: int, logs: dict = None):
        logs = logs or {}
        for metric, value in logs.items():
            dvclive.log(metric, value)
        dvclive.next_step()
        notify('pushover', user='foo', token='bar', message=f'epoch: {epoch}')
```

But having the notification step built inside `MetricLogger` would have some benefits like access to internals (i.e. `_metrics`) and configuration options in addition to hiding complexity to the end user.

However, I'm not sure if it is worth to implement this feature inside `dvclive` or if it would be better to keep `dvclive` as lightweight as possible.

**Comment by dmpetrov** [comment]
@daavoo I'm trying to understand the motivation behind this? 😄  
could you please elaborate on this? o you want to update the files more often? What `notify()` means?

**Comment by daavoo** [comment]
> @daavoo I'm trying to understand the motivation behind this? smile
> could you please elaborate on this? o you want to update the files more often? What `notify()` means?

Sorry about the lack of clarity. 

The motivation comes from working with deep learning models that take a lot of time to train (i.e. hours or days). When working under that circumstances we always ended up writing some sort of "notification" code to complement or integrate into the ml logger. 

This notification code takes care of sending a message to some platform (i.e. e-mail, slack / discord / telegram channel, etc) containing information like the number of finished epoch (a.k.a `step` in `dvclive`) and associated metrics. We also used it to inform when exceptions occurred during the training loop.  

`notify()` is usually a function that sends useful information as a message to an app. 

> 
> EDIT: do you have any references in other ml logger frameworks to this functionality?

I think that in other ml loggers we usually have an associated UI with a view that is automatically being updated as the plots/information are being logged (Related with this Studio issue: https://github.com/iterative/studio-support/issues/13)

In addition to that, some ml loggers also provide "notification" utilities:

- https://docs.wandb.ai/guides/track/advanced/alert
- https://www.comet.ml/docs/python-sdk/Experiment/#experimentsend_notification


Beyond existing functionality in other ml loggers, I have personally found different teams and open source communities solving this problem:

- https://github.com/huggingface/knockknock
- https://forums.fast.ai/t/training-metrics-as-notifications-on-mobile-using-callbacks/17330

**Comment by daavoo** [comment]
I just discovered another open-source tool focused on this kind of functionality:

https://github.com/labmlai/labml

**Comment by pared** [comment]
Related to #91

**Comment by daavoo** [comment]
Another open source tool:

https://github.com/aporia-ai/mlnotify

**Comment by daavoo** [comment]
Interesting integration between [DagsHub](https://dagshub.com/) and [New Relic](https://newrelic.com/) highlighting `alerts` as one of the main features:

https://dagshub.com/blog/real-time-machine-learning-monitroing-new-relic-dagshub/

**Comment by dberenbaum** [comment]
Related to https://github.com/iterative/dvclive/issues/91#issuecomment-1035015144, I think the most useful integration here would be making it dead simple to send full reports (similar to the html today) through supported channels.

For example, the slack api could probably be used generate a message with the metrics and plot images, and similar for email (personally, I would prioritize slack because it's more collaborative and probably easier for users to set up).

The local html generated now could just be one report/alert format in that case (and the cml markdown report another).

**Comment by daavoo** [comment]
> I'm not sure text-based alerts add enough value (we could instead have a doc or blog post showing how to use dvclive + https://github.com/liiight/notifiers). Full reports with plots seem like a more unique feature, and they extend dvclive's initial value prop of lightweight live monitoring for model training, providing serverless alerting and reporting anywhere without needing to access the training machine. Since a lot of training happens in headless environments anyway, this seems pretty useful to me. What do you think?

I think it's useful and immediate added value for DVCLive. 

I'm a little "worried" about how easy would be to maintain because Report Providers sounds like integrations potentially growing perpendicular to ML Frameworks.

So far, looking at slack and email APIs, it doesn't look that bad.

**Comment by dberenbaum** [comment]
@shcheklein mentioned that it might be worthwhile to look into RSS feed aggregators. There are some parallels in how RSS expects a particular schema of elements (https://validator.w3.org/feed/docs/rss2.html) and can publish them in a consistent format, so maybe it can give some ideas for how to implement.

**Comment by casperdcl** [comment]
So it's about tidying up this sort of thing? <img height=16px src="https://img.tqdm.ml/logo.gif" />

```python
from tqdm.contrib.{slack,telegram,discord} import trange

with trange(live.get_step(), epochs, unit="epoch") as pbar:
    for epoch in pbar:
        ...
        live.log("loss", loss)
        pbar.set_postfix(loss=loss)
        live.next_step()
```

i.e. providing a callback interface?

```python
live.set_callback(
    on_log=lambda name, metric: pbar.set_postfix({name: metric}),
    on_step=lambda new_step: print(f"starting epoch {new_step:>5d}"))
```

**Comment by dberenbaum** [comment]
I don't think we are likely to do this now that we have live metrics in Studio and other solutions exist for alerting.
