### ISSUE TITLE
logger: refactor initialization error message

### ISSUE THREAD

**Issue by pared** [iterative/dvclive#92]
After #67 we initialize logger in default dir `dvclive`.
In `next_step`, we rise `InitializationError`, which message suggests that `init` has not been called.
This situation actually happens only if we

1. Neve call `dvclive.init`
AND
2. Never call `dvclive.log`

So the error message is misleading. It should be refactored in a way that tells user he never called `init` nor `log`

**Comment by blacku13** [comment]
I would like to work on this

**Comment by pared** [comment]
@blacku13 I assigned you.
