### ISSUE TITLE
errors: get rid of DvcLiveError calls.

### ISSUE THREAD

**Issue by pared** [iterative/dvclive#93]
`DvcLiveError` is an error that should be an abstract exception that lets end user know where it did originated.
We should replace current occurences of `raise DvcLiveError` with particular errors with naming related to the cause.

**Comment by zili55** [comment]
Hello, can I take this issue?

**Comment by daavoo** [comment]
> Hello, can I take this issue?

Sure!

**Comment by jorgeorpinel** [comment]
Looks like this was fixed by https://github.com/iterative/dvclive/pull/135. Can we close this?
